### ISSUE TITLE
Error when converting to git repo

### ISSUE THREAD

**Issue by H3npi** [frej/fast-export#112]
i am trying to convert a mercurial project to git.
The local hg project is a fresh clone of a hg project.
The git repo was initialized with git init
The command i used from the git dir:

`/tmp/fast-export/hg-fast-export.sh -r /home/username/workspace/hgrepo`

and the Traceback i get:
```
Traceback (most recent call last):
  File "/tmp/fast-export/hg-fast-export.py", line 529, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/tmp/fast-export/hg-fast-export.py", line 405, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "/tmp/fast-export/hg-fast-export.py", line 364, in verify_heads
    sha1=get_git_sha1(sanitized_name)
  File "/tmp/fast-export/hg2git.py", line 110, in get_git_sha1
    l=subprocess.check_output(["git", "rev-parse", "--verify", "--quiet", ref])
  File "/usr/lib64/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by frej** [comment]
>   File "/tmp/fast-export/hg2git.py", line 110, in get_git_sha1
>     l=subprocess.check_output(["git", "rev-parse", "--verify", "--quiet", ref])

Figure out what the value of 'ref' is. The raised exception complains
that one of the arguments to execv is not a string and as it is the only
thing which is not a hard-coded string, it may give a clue about what's
wrong.

**Comment by H3npi** [comment]
Thanks for the answere!

when i am printing out the variable i get a list of heads (i guess):

```
refs/heads/master
refs/heads/test
refs/heads/hotfix/newEarGrubenwehr
refs/heads/hotfix/11982
refs/heads/hotfix/11980
refs/heads/hotfix/11948
refs/heads/develop
refs/heads/Change/11733
refs/heads/release/1.17.16
refs/heads/hotfix/11994
refs/heads/test2
refs/heads/hotfix/11951
refs/heads/hotfix/11937
refs/heads/hotfix/11921
refs/heads/hotfix/11992
refs/heads/feature/11933
refs/heads/feature/11890
refs/heads/hotfix/noticket
refs/heads/feature/11779
refs/heads/hotfix/11939
refs/heads/testing
refs/heads/hotfix/11902
refs/heads/hotfix/11900
refs/heads/hotfix/11878
refs/heads/hotfix/11775
refs/heads/temp/Tester
refs/heads/feature/11880
refs/heads/properBranchClosing
refs/heads/asd
refs/heads/hotfix/11759
refs/heads/hotfix/11840
refs/heads/hotfix/11813
refs/heads/hotfix/11812
refs/heads/hotfix/11810
refs/heads/hotfix/11727
refs/heads/hotfix/11697
refs/heads/hotfix/11612
refs/heads/hotfix/11486
refs/heads/hotfix/10750
refs/heads/feature/7687
refs/heads/hotfix/11896
refs/heads/feature/11713
refs/heads/hotfix/11276
refs/heads/hotfix/#9594
refs/heads/hotfix/#10343
refs/heads/feature/11446/11617
refs/heads/feature/11446/11515
refs/heads/feature/tester
refs/heads/feature/9286
refs/heads/feature/11828
refs/heads/feature/11783
refs/heads/feature/11554
refs/heads/feature/11547
refs/heads/feature/11157
refs/heads/feature/10759
refs/heads/feature/#7180
refs/heads/#5694
refs/heads/
```

The only thing i see which may be an issue are the branches with a "#" in it. Or maybe the last call which is just "refs/heads/" could be the issue.
As far as i can see everything in there is a string.

**Comment by H3npi** [comment]
> How did you print the string? Did you ensure that it is printed unbuffered to stderr?
I printed it by adding 
`sys.stderr.write(refs)`
before line 110 in hg2git.py

> Can you share the hg-repo?
Sadly i cannot share the repo. (Company internal)

> Also, have you tried converting another repo just to be sure this is not specific to this particular repo?
Yes i converted 6 other repos sucessfully so far (more comming)

> If you list the heads in the hg repo, are there any heads which do not appear in the list?
When i use  `hg heads` i see 44 open heads, in the list of `refs/heads/` are 58 entries.
There are some entrys in `hg heads` which are not in `refs/heads/` like `wildfly10/responsive`

I don't know whether this is important or not, but the repo is quite big (in size and history) over 20k changesets and around 4 GB in size.

**Comment by H3npi** [comment]
i did run this script:
`https://gist.github.com/FernFerret/3178035#file-branchfind-sh`

it showed up some branches which were already closed. Could there be a problem with closed branched showing up as multiple heads, when these branch names were used 2 or more times?

**Comment by frej** [comment]
So it looks like you have done everything correctly.
Multiple heads has always been a problem when converting to git, so the mismatch between hg heads and git heads could be significant. That the last printout is `refs/heads/` is strange, is there perhaps  a branch with an empty name on the hg-side?

The strangest thing is that the thrown exception seems to indicate that `subprocess.check_output` feeds `execv` something that isn't a string, and we should have seen that in the printout, why not try it again with `sys.stderr.write(repr(ref))` to see if there are any strange characters hiding in there.

Another thing to try could be do create a branch mapping for each head listed by  `hg heads` and give each branch a harmless name like `hg-branch-<number>` and see if the conversion works then.

**Comment by H3npi** [comment]
This looks like an empty branchname to me:
`'refs/heads/\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`
Its the last line of `sys.stderr.write(repr(ref))`.

i'll doublecheck this and post back asap

**Comment by H3npi** [comment]
ok, i doublechecked with a coworker... there was a branch with an empty string as a name. This branch got closed, i guess the script also tries to convert the closed named branches..

**Comment by H3npi** [comment]
found a workaround!

Since the `sys.stderr.write(repr(ref))` printed out `'refs/heads/\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'` i created a branch mapping:

"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"="EMPTY"

Now the migration is working. This issue can be closed!

**Comment by frej** [comment]
> found a workaround!
>
> Since the sys.stderr.write(repr(ref)) printed out 'refs/heads/\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' i
> created a branch mapping:
>
> "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"="EMPTY"
>
> Now the migration is working. This issue can be closed!

That was what I was going to suggest, you beat me to it.

**Comment by AdamMcArdle** [comment]
Nearly two years on and this has bailed me out of the same issue. We had a shorter string of \x00s but it was the same problem.
