### ISSUE TITLE
What is the way to do it work in Windows?

### ISSUE THREAD

**Issue by serge987** [frej/fast-export#113]
_**(the issue is discussed on the SO [here](https://stackoverflow.com/questions/49233515/migrate-hg-to-git-via-fast-export-in-windows/49237922?noredirect=1#comment85481822_49237922))**_
I never managed to do it working in windows... Is there a way to be more specific on the commands to run?
where shoud these commands be launched? in the git repository or in the mercurial one?
Should or not the "git" repository folder be embedded/part of mercurial one?
Should or not python be installed, and is there a difference in launching `.sh` or `.py` command?

Please if possible provide an example with a real path, to clear that questions.
Say, take the "D:\MyProject" folder, that contains the ".hg" and do a more concrete example without the "whatever", cause could be disturbing for some newbies...

Say I have `D:\MyProject` containing the `.hg` directory and the project code files, I 

 * downloaded the `fast-export` files in the "D:\fast-export-master" folder, 
 * created a new directory `D:\MyProject-git`
 * launched in that `D:\MyProject-git` the `git init` command (a new `.git` directory appeared then);
 * now from the same `D:\MyProject-git` i did  
` ..\fast-export-master\hg-fast-export.sh -r "D:\MyProject"`

now strange things starts happening, a command line window appeared and disappeared so quickly I didn't understood what happened, so I relaunched the previous command in a hope to see the message... I should  try tens of times until able to capture in the printscreen the command-line message, that says strange things: 

> which: no D:\fast-export-master\hg-fast-export.sh in (/c/Users/xxx/bin:mingw64/bin:/user/local/bin:/usr/bin:/bin/mingw64/bin:/usr/bin:/c/Users/xxx/bin:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32 *[...etc...etc...]*)

I wonder what is the problem and how to solve it...

**Comment by frej** [comment]
Fast export was created on and for unix-like machines. As you have seen on the web some brave souls have apparently managed to run it on Windows. My guess is that they run it within a cygwin environment where the standard unix utilities are available. The error message above, about a missing `which` and that your commands use DOS path delimiters seems to indicate that this is not what you are doing.

Running bash-scripts and python programs on Windows is way outside my area of expertise, your best bet is asking for help at Windows or Python fora.

**Comment by serge987** [comment]
Knowing that the [Desktop OS global share](http://gs.statcounter.com/os-market-share/desktop/worldwide) is 82.56% for Windows, 12.36% for OS X, 2.62% for other OS and only 1.46% for Linux (around 1% for the Chrome OS), I think is worth mentioning in ReadMe that your solution is for made for linux users. However, in the GitBash using `/c/Users/myName/etc/etc` paths format and also another options, I managed to make it work for the main dev OS...

**Comment by frej** [comment]
Remember that hg-fast-export has been created by unpaid volunteers to solve their problems in their working environment and not to capture market share. Being open source and available for free allows it to be adapted by anyone to different platforms and use cases. 

Why not give back to the community and contribute a `README.Windows` describing how to use fast-export on windows?

**Comment by sbloom** [comment]
I was able to run this on Windows by using Git Bash prompt (Cygwin will work also), and the latest update by Frej, which solved my 'latest' HG problems (Thanks Frej!)
