### ISSUE TITLE
hg-fast-export fails with "error: cannot lock ref"

### ISSUE THREAD

**Issue by pini-gh** [frej/fast-export#115]
Hi,
I'd like to locally convert this mercurial repo to git: https://bitbucket.org/gplugin/main/src
But it fails with:
`error: cannot lock ref 'refs/heads/feature/lua/luajit': 'refs/heads/feature/lua' exists; cannot create 'refs/heads/feature/lua/luajit'`

Any clue?
Thanks,
_g.

**Comment by pini-gh** [comment]
This is because the hg repo has these two branches:
```
feature/lua/luajit           645:dcfa40915736 (closed)
feature/lua                  417:89e9f50c8ecd (closed)
```
The error message is issued by `git fast-import` which can't create `refs/heads/feature/lua/luajit` when `refs/heads/feature/lua` already exists.
An easy workaround is to add '/' to the sanitized char set for branch names in `hg-fast-export.py`:
```
--- /usr/share/hg-fast-export/hg-fast-export.py.orig    2018-03-15 23:45:42.585790441 +0100
+++ /usr/share/hg-fast-export/hg-fast-export.py 2018-03-15 23:45:50.617688450 +0100
@@ -145,7 +145,7 @@
     return name
 
   n=name
-  p=re.compile('([[ ~^:?*]|\.\.)')
+  p=re.compile('([[/ ~^:?*]|\.\.)')
   n=p.sub('_', n)
   if n[-1] in ('/', '.'): n=n[:-1]+'_'
   n='/'.join(map(dot,n.split('/')))
```

**Comment by frej** [comment]
Did you read the comment at the start of `sanitize_name` in the current master branch? Also see #108 for why this patch will not be accepted.

**Comment by pini-gh** [comment]
The version installed on my box doesn't have this comment; nor the '-B' and '-T' option. I realize that this tool hasn't been updated since 2014 in debian [1]
[1] https://tracker.debian.org/pkg/hg-fast-export
I gave a test at the current master branch and using '-B' with the file below solved my problem.
```
$ cat ../branches.map 
"feature/lua/luajit"="feature/lua-luajit"
```
