### ISSUE TITLE
Invalid file format when using -A authors,txt extension

### ISSUE THREAD

**Issue by rishitborad** [frej/fast-export#116]
I have been trying to convert my mercurial repositories to GIT repositories. My issue is an extension of issue #80 and #15. When I am trying to use -A authors.txt I get an error saying **_invalid file format in authors.txt, line #_** for all the lines present in author file. 

I have tried creating and editing the author file using `hg log | grep user: | sort | uniq | sed 's/user: *//' > ../authors` command as mentioned here _https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git#Mercurial_. By editing i mean i added <>=devnull <devnull@localhost> at the first line. 

I am not sure what is the right format for the file or if it is complaining about the wrong format of the authors' entries in the file. what is the right format of the entries inside the authors' file? Or what is the right file format? Or what am I doing wrong?

I tried to re-generate this problem with the mercurial repos I was able to migrate successfully. And I have the same problem there. While migrating these repos I did not use "_-A authors_" option.

Thanks in advance.
Regards,
Rishit

**Comment by frej** [comment]
> I am not sure what is the right format for the file or if it is
> complaining about the wrong format of the authors' entries in the
> file.

Quoting from the README:

The file should contain lines of the form `"<key>"="<value>"`. Inside
the key and value strings, all escape sequences understood by the python
`string_escape` encoding are supported. (Versions of fast-export prior
to v171002 had a different syntax, the old syntax can be enabled by the
flag `--mappings-are-raw`.)

There is even an example following this description.

**Comment by rishitborad** [comment]
That is amazing how quickly you answered. Thanks for the swiftness and the answer. It worked, but only the lines that had <key> and <value> both. I guess I would not do anything to the authors I don't want to remap and let the fast-export fail for those author lines. I just wonder if there will be any aftereffect for doing this.

Thanks
Rishit

**Comment by frej** [comment]
I've sent some patches to the authors of the Pro Git book to update the example to match the current version of fast-export, hopefully that will prevent anyone else from encountering the same problem. The patches are accepted, so I guess that eventually they will show up in the web-version.

Now for the question about running without a mapping file. I'd say that it depends on your level of ambition for the conversion. If your current repo is the result of  long chain of historical conversions, i.e. RCS -> CVS -> SVN -> HG and you want to clean up the author information, then canonicalizing the author information as described in the Pro Git book is the way to go. That way you can be sure to only produce well-formed authors and not forget rewriting historical identities.

If you just want a quick conversion for your own use or don't care about historical authors you can just try to do the conversion. Remember that if there isn't a matching mapping, the author string will be used unchanged. If git-fast-import encounters an author string Git won't allow, it will crash and report the error. Then you can add a mapping to the author file and restart. The only drawback is the time you have to spend retrying the conversion.

**Comment by rishitborad** [comment]
> Remember that if there isn't a matching mapping, the author string will be used unchanged. If git-fast-import encounters an author string Git won't allow, it will crash and report the error. Then you can add a mapping to the author file and restart. The only drawback is the time you have to spend retrying the conversion.

I am using **unchanged** author strings for some of the authors I don't want to remap. This is generating the same problem for those lines because they don't have double-quotes around the key and no value present at all. My question was if I can ignore the errors without having any consequences. In other words, I have an author file which has re-mapped authors in key=value format inside double quotes and some original (not re-mapped) authors. This creates trouble because original authors are not inside double-quotes. Can I just ignore the troubles and be happy with the remapping of the new authors or do I have to make it right? 

I hope you see what I am saying.
Thanks,
Rishit

**Comment by frej** [comment]
> I am using unchanged author strings for some of the authors I don't want to remap. This is
> generating the same problem for those lines because they don't have double-quotes around the
> key and no value present at all. My question was if I can ignore the errors without having any
> consequences. In other words, I have an author file which has re-mapped authors in key=value
> format inside double quotes and some original (not re-mapped) authors. This creates trouble
> because original authors are not inside double-quotes. Can I just ignore the troubles and be
> happy with the remapping of the new authors or do I have to make it right?

So that's what you meant. Yes, it's safe to keep the malformed lines, a
line that fails to parse is just ignored.

**Comment by rishitborad** [comment]
Great. So Long, and Thanks for All the Fish
