### ISSUE TITLE
error: cannot lock ref

### ISSUE THREAD

**Issue by tbm** [frej/fast-export#117]
I'm getting the following error:

```
Issued 4530 commands
error: cannot lock ref 'refs/heads/ingest/importers/filetype_fix': 'refs/heads/ingest' exists; cannot create 'refs/heads/ingest/importers/filetype_fix'
git-fast-import statistics:
```

Steps to reproduce:

```
hg clone https://bitbucket.org/blais/beancount/src hg
git clone https://github.com/frej/fast-export
mkdir beancount
cd beancount
git init
hg-fast-export -r ../hg
```

**Comment by frej** [comment]
> error: cannot lock ref 'refs/heads/ingest/importers/filetype_fix': 'refs/heads/ingest' exists; cannot create 'refs/heads/ingest/importers/filetype_fix'

Git branch names follow the same rules as filenames. Just like you can't
have a file named `./foo` and a directory also called `./foo` in the
same directory, you can't have `ingest` as a branch (corresponding to a
file in the FS case) and then expect to create another branch named
`ingest/importers/...` (corresponding to a subdirectory of a file).

What you want to use is branch mapping file (the `-B` flag) to
deconflict your branch name space.

**Comment by tbm** [comment]
Thanks @frej, this makes sense.  However, maybe you could improve the error to be more user-friendly.

**Comment by frej** [comment]
> Thanks @frej, this makes sense. However, maybe you could improve the error to be more user-friendly.

As it is git-fast-import that produces the error message and its
documentation only promises a non-zero exit status on errors, it's not
much fast-export can do.

**Comment by tbm** [comment]
Ok, feel free to close.

Of course, ideally the script would check the Mercurial branches before conversion to see if there's a conflict, but this is more than you may want to do. :)

Thanks for your fast response!

**Comment by frej** [comment]
> Of course, ideally the script would check the Mercurial branches
> before conversion to see if there's a conflict, but this is more than
> you may want to do. :)

Your guess is right on the money, in order to do the validation
properly, fast-export would have to replicate most of the functionality
of fast-import. It's not just branches, filenames, authors, and dates
would also have to be checked.

Eventually all the common reasons will be covered by closed github
issues :)

**Comment by tbm** [comment]
Thanks for the tool!  I used -B and it worked as expected.
