### ISSUE TITLE
git version 2.17.GIT : .../git-sh-setup: line 46: ..../git-sh-i18n: No such file or directory

### ISSUE THREAD

**Issue by mamopa** [frej/fast-export#119]
Hello,
I know there was an similar issue in the past.
It seems, that this problem exists again, at least in the latest version.

How to solve this problem now?

**Comment by frej** [comment]
A truncated error message does not provide enough information for me to help you. What are you trying to do, how are you doing it, in what environment, and are you using the latest fast-export?  Please have a look at  [this blog post about writing effective bug reports](https://www.viget.com/articles/tips-for-writing-better-bug-reports). 

Does stand alone git work for you?
