### ISSUE TITLE
Conversion doesn't bring all my branches to git

### ISSUE THREAD

**Issue by jcollinsJIA** [frej/fast-export#120]
I am trying to convert my hg repo to git.  When I run the command, ~/dev/fast-export/hg-fast-export.sh -r ~/dev/2095/ --force --hgtags -A ~/dev/authors.txt -B ~/dev/branches.txt -T ~/dev/tags.txt

It doesn't bring all my branches or tags from the hg repo. I ran hg branches on the repo and used that to make my branches mapping file, to look something in the form of, "branchname"="branchname", same with tags.  Am I missing something?

**Comment by frej** [comment]
> Am I missing something?

Not anything obvious. Does fast-export complain about anything? Can you
say anything about the branches/tags that are missing?
