### ISSUE TITLE
System requirements unclear

### ISSUE THREAD

**Issue by rinu** [frej/fast-export#121]
The readme really should say this thing strictly requires python 2.7 and forget running on Windows. Would have saved me an hour of debugging. I installed pip, upgraded to python 3 and so on. Guess I'll start over on a different computer.

**Comment by rinu** [comment]
Actually, the system requirements should also be specified in the guide that got me here.
https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

**Comment by frej** [comment]
> The readme really should say this thing strictly requires python 2.7
> and forget running on Windows. Would have saved me an hour of
> debugging. I installed pip, upgraded to python 3 and so on. Guess I'll
> start over on a different computer.

I have had some reports from users that after some work have managed to
get it to work on Windows, the key thing seems to be to run it under
cygwin.

Unfortunately after the initial frustrated report, they have all gone
silent when I have asked if they could submit a README.windows
explaining how to do it. A contributed patch is always appreciated...

**Comment by frej** [comment]
> Actually, the system requirements should also be specified in the guide that got me here.
> https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

Then I suggest you submit a patch to them, they have been very
responsive when I have proposed updates to make their examples work with
the current fast-export version.

**Comment by rinu** [comment]
Converted my repo on Windows successfully now, my issues were not related to the OS.

**Comment by frej** [comment]
@rinu, any chance I can get you to write down what's missing in the readme for running on Windows, either in README.md or in a new README.windows?

**Comment by rinu** [comment]
Basically all I want you to add to the beginning of the readme Usage section is this:
```
This project depends on Python 2.7 and the Python mercurial package.
If python is not installed, install it before proceeding.
The mercurial package can be installed with `pip install mercurial`

If you're on Windows, run the following commands in git bash (Git for Windows).
```

**Comment by frej** [comment]
> Basically all I want you to add to the beginning of the readme Usage
> section is this:

Thanks, I'll incorporate a version of this the next time I work on
fast-export.
