### ISSUE TITLE
.git/HEAD is untracked after conversion

### ISSUE THREAD

**Issue by hardysim** [frej/fast-export#123]
I'm trying to convert a repo from HG to Git using the following command. The `--force` is added instead of `git config core.ignoreCase false`.
```
git init
../fast-export/hg-fast-export.sh -r ../hg-repo/ --force -A ../fast-export/mappings.txt
```
which seems to work but **I cannot push the repo to my git-server**. 

When pushing it tells me, that some object contains `.git`.
Plus, I cannot do `git checkout HEAD`. It breaks with the following error:

```
$ git checkout HEAD
error: The following untracked working tree files would be overwritten by checkout:
        .git/HEAD
        .git/config
        .git/description
        .git/info/exclude
Please move or remove them before you switch branches.
Aborting
```

So it seems like these files are somehow corrupt.
When deleting them, the repo is broken and `git status` etc. does not work anymore.

Any ideas?

**Comment by hardysim** [comment]
Oh OK, my fault. I had managed to commit those files to the mercurial-repo.
After [removing those files from the mercurial-history](https://www.jitbit.com/alexblog/232-removing-files-from-mercurial-history/) and everything is working now. Close.

**Comment by frej** [comment]
> The --force is added instead of git config core.ignoreCase false.

In most cases, giving --force to hg-fast-export.sh is not equivalent to
core.ignoreCase=false.

> which seems to work but I cannot push the repo to my git-server.
>
> When pushing it tells me, that some object contains .git.

Please quote the full error message, not your interpretation of it. How
did you try to push, which branch did you push or did you use --mirror?

> Plus, I cannot do git checkout HEAD. It breaks with the following error:
>
> $ git checkout HEAD
> error: The following untracked working tree files would be overwritten by checkout:
>         .git/HEAD
>         .git/config
>         .git/description
>         .git/info/exclude
> Please move or remove them before you switch branches.
> Aborting

On which branch are you working? What does 'git branch -a' and 'git
status say'? Looking at the filenames it almost looks like you have
managed to create a git repo inside a git repo. Maybe try starting over
in a clean empty directory.

**Comment by hardysim** [comment]
@frej thx for your feedback 😄 but I already solved it. You're right - there have been some git-files already in the mercurial-repo. I removed them and converted the repo again from hg to git and now everything is working.
