### ISSUE TITLE
Support line endings conversion

### ISSUE THREAD

**Issue by Himura2la** [frej/fast-export#126]
It would be very useful to perform text transformations on import. In hg line endings are not enforced, but git ecosystem loves LF.

I guess there is some place in the code to add a kind of `.replace("\r\n", "\n")`

**Comment by frej** [comment]
What about binary files? Please have a look at #95 for a previous discussion about automatic line ending conversion and what I would require for a patch to be accepted.

**Comment by Himura2la** [comment]
Sorry for not checking the existing tickets. I think filter-content is a great solution
