### ISSUE TITLE
failed to import extension hgext.git: No module named peer

### ISSUE THREAD

**Issue by nobody93** [frej/fast-export#135]
That problem is gone when cloning from git://repo.or.cz/fast-export.git.

Hi,

I made a clone from the master branch, running  it in Ubunbu 16.04, I made a clone from bitgucketgit project, cd t othe BitBucketGitProject, then running hg-fast-export.sh, I've got following errors. I've already installed mercurial-git package, what am I missing here?

$ dpkg -l mercurial-git
ii  mercurial-git  0.8.5-2      all          Git plugin for Mercurial

BitBucketGitProject $ ../../fast-export/hg-fast-export.sh -r ../MyMerucurialProject 

*** failed to import extension hgext.git: No module named peer
Error: Branch [master] modified outside hg-fast-export:

**Comment by frej** [comment]
The mercurial-git package is a Git plugin for Mercurial, it is not related to hg-fast-export. In #136 it looks like you have figured out how to install Mercurial proper, if so please close this ticket.

**Comment by frej** [comment]
No response, closing.
