### ISSUE TITLE
GPG sign exported commits?

### ISSUE THREAD

**Issue by bumblebritches57** [frej/fast-export#142]
Is there a way to sign all of the commits as they come into git?

It sounds like your filter-pipe might work, but I'm not entirely sure how I'd do that on a commit by commit basis.

**Comment by frej** [comment]
> Is there a way to sign all of the commits as they come into git?

The man page for git-fast-import (which fast-export uses) says: "Signing
annotated tags during import from within fast-import is not supported.",
so I'd say no.

You could probably do the signing after the conversion using git rebase
--root.

> It sounds like your filter-pipe might work, but I'm not entirely sure
> how I'd do that on a commit by commit basis.

If it's --filter-contents you refer to, that won't work as it processes
one file at a time, not commits.

**Comment by bumblebritches57** [comment]
I did git rebase sign like you suggested, the problem is, the pack file doubles because it's storing the unsigned copies as well.

and I used all of the prune, expire=all, gc, repack, etc commands I know of and it didn't reduce it like it should.

**Comment by frej** [comment]
> I did git rebase sign like you suggested, the problem is, the pack
> file doubles because it's storing the unsigned copies as well.

Have you tried pushing just the signed branch(es) to an empty repo?

**Comment by bumblebritches57** [comment]
I signed it in the master branch, but that's a good idea, I'll try creating a new branch, signing that, then pushing it to an empty repo.

**Comment by bumblebritches57** [comment]
That did seem to work better, thanks.
