### ISSUE TITLE
Warning: Not updating refs/heads/** (new tip ** does not contain **)

### ISSUE THREAD

**Issue by prabilash** [frej/fast-export#145]
Hi - Am trying to convert my mercurial project to git using fast-export. 
Mercurial version: 4.6
Python: 2.7.15
Fast export version: v180610

I get the below warning during the conversion process and not sure how to proceed. Any help would be very appreciated. Apologies, i wont be able to share the hg repository.
 
Warning: sanitized tag [Unicorn release] to [Unicorn_release]
Exporting tag [Unicorn_release] at [hg r10195] [git :10196]
Issued 10576 commands
warning: Not updating refs/heads/Llama_NewDesktopCheckout_FoodSubs-Pahd-4044 (new tip f843de57c97fa9609fa8d1648f7feeadffc8a3f7 does not contain 1465ae6e2a0774ca9b5aeaed1cf9f9a360a97268)
git-fast-import statistics:

**Comment by frej** [comment]
Fast-import performs a sanity-check to ensure that a branch update is what in a pull-context is called a fast-forward. The warning is from that check and as it fails, fast-import won't update the branch. I would guess one of the following things has happened:

* The built-in branch name sanitation or you branch mapping file has mapped two or more hg-branches to the same name.
* You are running on a file system which is case-insensitive and you have two or more branch names which differ only in the case of their names. As git represents branches as files in `.git/refs/heads/`, it has no way to distinguish between branches `A` and `a` if the file system is case-insensitive. The solution is to use a branch mapping file to ensure that they are given unique names after conversion.

**Comment by prabilash** [comment]
thanks, you were right. There were 2 branches with identical names in the mercurial repository that differed in only the case. I used the branch mapping file to map them to distinct branches and conversion went through fine.
