### ISSUE TITLE
add submodules urls

### ISSUE THREAD

**Issue by kikeenrique** [frej/fast-export#150]
Hi,
First of all, thanks to all the collaborators of this project. Thanks to that, I’ve almost finished a big mercurial to git migration, including subrepos. About 6 repositories, up to 5 years of history, 4000 commits.

But, I've found one missing point. 
After performing a repo with subrepos migration, I've ended up with a .gitmodules that does not point to a git url, but to a local path used in the migration.
That means that other team members, after cloning the main repo, won’t be able to initialise those git submodules.

In order to fix this point, **I would like to ask if it would it be feasible to add the repos url in the submodule-mappings file**(or whatever mechanism needed) **in order to use those urls in the .gitmodules, instead of the local paths**.

Modifying the .gitmodules with those urls in a commit after the migration is not a solution, because any commits to git break any subsequent import(as documentation explains). 
And I would need some future imports. The reason is that’s some of these subrepos would not yet be used in git, but in mercurial, for a period of time. The git repos would be kept in "migration state" mode, that is, they would be updated with more imports as original commits would be done in mercurial for some time. That's because they are common repositories used in other repositories that would not be migrated soon. 

I'm open to clarifications or even guidance in what would be needed to implement to fix this in order to do it myself.

Thanks for your time and dedication

**Comment by frej** [comment]
I think conventional wisdom is to give the path to the sub repos as relative paths, as in the readme. That way they will stay valid after conversion, given that you have the same relative layout on the public server.

@johannesc anything to add?

**Comment by johannesc** [comment]
Hi, 
I also recommend using relative paths as that makes is possible to change server URL without changing the .gitmodules file (and the older version of that file).

**Comment by kikeenrique** [comment]
Thanks a lot for your reply.
I didn't knew about the use of relative paths for submodule URLs.
I've just tested it and works as expected.
