### ISSUE TITLE
--hg-hash usage

### ISSUE THREAD

**Issue by siaspa** [frej/fast-export#154]
I'm new to Git and I'm converting a large HG project. Fast-export works very well, except for hg-hash (but  maybe there's something I'm using in the wrong way). I'm using the --force --hg-hash option. According to documentation, I was expecting to find a Git note added to each commit with the HG hash, but there were no notes at all.

Inspecting the .git folder i found 2 files:

hg2git-marks
	{hg2git-marks_id} 	{git-hash}
	
hg2git-mapping 
	{hg-hash}   {hg2git-marks_id - 1} 

Reading these files I should be able to add notes to each git commit, but I want to be sure that I used the tool correctly.

Thank you

**Comment by frej** [comment]
The `hg2git-marks` and `hg2git-mapping` are not intended for user consumption.

The key is in the help message for --hg-hash "Annotate commits with the hg hash as git notes in the _hg namespace_." What does `git notes --ref hg list` say in the converted repo?

**Comment by siaspa** [comment]
At the moment I don’t know what does ‘hg namespace’ mean, but I’ll take a look to understand it.  However, running the command you told me produces a list of rows with two columns. The first one is not the hg hash, I don’t know what it is, but the second one is the git hash.

**Comment by frej** [comment]
The output from  `git notes --ref hg list` tells me that notes were created. As the `hg` namespace is not by default shown by git you will have to tell git to show it. For example, run `git log --notes=hg <commitish>` and you will see the notes. Check the git configuration variables `core.notesRef` and `notes.displayRef` (check the man page for `git notes`) for how to change the default.

**Comment by siaspa** [comment]
It works! Thank you!
