### ISSUE TITLE
Branch name with two or more `_`  character is sanitized

### ISSUE THREAD

**Issue by vo-va** [frej/fast-export#155]
Why two or more `_` character in branch name are sanitized to one character?
git-check-ref-format(1) it does not forbid using two `_` characters in a row.
Also I tried to use file to mapping branch name for example with this content

```
"_____v2"="_____v2"
```

It does not work for me.

**Comment by frej** [comment]
That code has been there since forever, so we can't change it as it
could break existing working conversions.

Please provide a link to the repo which exhibits this problem or give me
a set of commands which creates such a repo.

**Comment by vo-va** [comment]
Sorry, It is private project.  
You can reproduce this issue simply by creating new branch with two `_` characters in row. For example
```
git checkout -b a__b
```
This branch will lead to warning.
```
Warning: sanitized branch [a__b] to [a_b]
```
These two lines cause my trouble https://github.com/frej/fast-export/blob/master/hg-fast-export.py#L231 
So I know which lines I can patch to mitigate my trouble. But I don't understand why two or more `_` forbidden.

**Comment by frej** [comment]
The only person knowing why two or more `_` are forbidden is the original author. As we don't want to break existing conversions we can't just change the code.

The right way to handle this is along the lines of 7f42b8ea716ea115ab69ce684885dcf32a3e49f4 in the  user-support/fix-for-vo-va  branch, try it out. It should make your remapping file work. Before pushing this to master I have to make sure the user is properly warned before getting the new behaviour.

**Comment by vo-va** [comment]
Sorry for delay.
Yes this fix works for me - if branch mapping is specified two or more `_` will not be removed.
