### ISSUE TITLE
Instructions in the readme do not work

### ISSUE THREAD

**Issue by ilyapopov** [frej/fast-export#158]
After today's bitbucket announcement of terminating HG repository support on 1 june 2020 I am exploring solutions of converting my hg repositories to git. I am trying to follow instructions given in README, but I encounter the following errors:

```
Error: No --marks option given
```

and then:

```
Error: No --mapping option given
```

These options are not mentioned in readme and I am not sure what to do about these.

**Comment by ilyapopov** [comment]
Sorry, turns out to be my mistake. Accidentally run the `.py` file instead of `.sh`.

**Comment by frej** [comment]
> Therefore, I would suggest to remove that `.py` part in the README
> title.

Patches welcome.
