### ISSUE TITLE
error: Invalid Path '.../static/selectize.js/.git/FETCH_HEAD' on checkout after conversion

### ISSUE THREAD

**Issue by orutherfurd** [frej/fast-export#159]
After running hg-fast-export on a mercurial report that had a clone of an git repo in it, I'm unable to checkout head after the conversion. Running `git reset HEAD`, I get:

```
error: Invalid path '.../static/selectize.js/.git/FETCH_HEAD'
fatal: make_cache_entry failed for path '.../static/selectize.js/.git/FETCH_HEAD'
```

**Comment by frej** [comment]
That's not a currently supported use case. Why do you have a git repo inside a hg repo? Is it a bare repo or does it have a checked out state too? Have you been using hg to do backups or are you perhaps debugging git and want to preserve snapshots of various git states?

If the stored snapshot has a dirty checked out working directory I don't think you can even map this to a git submodule or git-subdir model. Regardless of the bare / working directory issue, at least git submodule stores the submodule's objects in the same git object database as the parent which means you won't be able to preserve bit-by-bit identical git snapshots.

**Comment by orutherfurd** [comment]
Hey, it was just a snapshot of a js library downloaded from github and just didn't go through the process of removing the .git directory. I can just run an hg to hg conversion stripping out the .git before converting to git.
