### ISSUE TITLE
fast-export/hg-fast-export.sh: line 179: python2: command not found 

### ISSUE THREAD

**Issue by VitaliyAT** [frej/fast-export#160]
I can't convert any hg to git and got line as in title, 179 line it's a comment "# move recent marks cache out of the way..."
I have both pythons installed: 2.7.16 and 3.7.3 Also Win 10

**Comment by frej** [comment]
I can guess that the line number is your shell being confused about the redirect/exec magic ending at line 179. Is `python2` in you path? #143 looks suspiciously like this issue.

**Comment by clach04** [comment]
The workaround of setting PYTHON to python worked for me on my Microsoft Windows machine but applying the code fix is easier.

I.e.

    env PYTHON=python hg-fast-export.sh  ....

**Comment by frej** [comment]
Let me known if the patch in f57fba000b9f15ebcb68e898db23ef02a23eaefe doesn't fix your problem @VitaliyAT.

@clach04: Regarding your patch in 162ba4a3f2cb3c977917e3e270720fe9ce10ca7e: Checking for a particular OS and then assuming that a particular feature behaves in a certain way is known to not be robust. It's much better to check the feature instead, as that will do the right thing on any OS or platform. In this case the patch in f57fba000b9f15ebcb68e898db23ef02a23eaefe will (hopefully) work both on windows and Arch-linux (the reason for [PEP 394](https://www.python.org/dev/peps/pe)).
