### ISSUE TITLE
Conversion gotcha if the source repo contains a file named .git

### ISSUE THREAD

**Issue by walkindude** [frej/fast-export#166]
Hello, this is _not_ a urgent issue, more like a gotcha/caveat.

I have used fast-export to convert a repo of a project containing a tiny plain text file named `.git`, which was part of a small library whose sources had been included in a subdirectory of the source tree. Inside the file was a path that pointed to a directory two levels up, but the actual contents didn't seem to matter.

When the conversion was done, this happened (after running `fast-export` on a repro repo with just a .git text file committed): 

    $ git status

    On branch master
    Changes to be committed:
      (use "git restore --staged <file>..." to unstage)
            deleted:    .git

    $ git checkout HEAD

    error: Updating the following directories would lose untracked files in them:
            .git

    Aborting

    $ git reset --hard HEAD
    error: invalid path '.git'
    HEAD is now at 2a047b8 create .git file

I solved the problem easily by simply getting rid of the file which had no business being there in the first place and ran a new conversion.

So it seems that one of the tools in the chain does not like files named `.git`.

Not surprising, since Mercurial itself will refuse to initialize a repository in a directory that contains such a file, saying `abort: Cannot create a git repository.`

Again: not a problem that needs urgent attention, maybe just a small note on the README would do. I can see how it could potentially impact other people and cause some head scratching.

Thanks for this wonderful tool, I've tested it successfully with several different repos and this is the only glitch I noticed.

**Comment by frej** [comment]
This looks related to #159, there it was a proper git repo, but apparently things will break as soon as something looks like a git repo.

**Comment by frej** [comment]
LGTM, thank you for your contribution!
