### ISSUE TITLE
Conversion with subrepos failed

### ISSUE THREAD

**Issue by JustDevZero** [frej/fast-export#171]
Hello there,

I thing that something is wrong with fast-export, or my repos or something.

I have a project called:
popeye

Here I have a folder named:
utils

That point to a subrepo called:
fibre-popeye

According to the readmes, I should first convert fibre-popeye to a git repo.

That was done with this command:

`mkdir ~/Projects/utils && cd ~/Projects/utils && hg-fast-export.sh -r /home/zero/Projects/fibre-popeye --hgtags -A /home/zero/Projects/authors.txt`

I didn't find a single error nor warning. Seems to be full converted without any integrity errors.

Then, I try to convert the main repo:

`mkdir utils && cd utils && hg-fast-export.sh -r /home/zero/Projects/fibre-popeye --hgtags -A /home/zero/Projects/authors.txt`

`cd .. && hg-fast-export.sh -r /home/zero/Projects/popeye --subrepo-map=/home/zero/Projects/submodule-map.txt --hgtags -A /home/zero/Projects/authors.txt`

Where submodule-map.txt have this content:
`"utils"="../utils"`

When It's finished there's no .gitmodules file, neither any reference to the subrepo.

Trying to understand what happened I noticed there are this time, multiple warnings with stuff like this:

`Warning: Could not find hg revision 1eaa12e8488f925dfcb2f6b4a23a5fabf052765c for utils in git ../utils/.git
`

If I seek that revision on the fibre-popeye utils, I detected that they're all from the default branch. But... If I see the converted git utils repo I can found this commits:

```
hg glog -r e1bc20b60fb25552433a3138fe6d4bbd107af4cf
o    Branch: default
|\   Rev: 412: e1bc20b60fb25552433a3138fe6d4bbd107af4cf
~ ~  Parent: 412:e1bc20b60fb2
     Author: HIDDEN_FOR_PRIVACY
     Description: Merge Popeye migration with default.
     Date: 2011-11-02 16:30 +0100
     Files: data/transform.py static/css/backoffice/components.css static/css/backoffice/forms.css static/js/backoffice/components.js

```

```
commit bc818cc02be39d232405dc40c63519578b1072ab
Merge: 45dba3c dd81059
Author:  HIDDEN_FOR_PRIVACY_BUT_CHANGED_EMAIL_FOLLOWING_AUTHORS_MAPPING
Date:   Wed Nov 2 16:30:17 2011 +0100

    Merge Popeye migration with default.
```

May is this failling due to the author mapping?

If so... which solution do I have? Ignoring mapping for subrepo? Will it be enough with the flag for hg-hashes ?

Thanks for all.

**Comment by JustDevZero** [comment]
Update: it looks is due to the author mapping. I tried to convert the subrepo without author mapping and everything went like a charm.

**Comment by frej** [comment]
Are you sure? From the commands you show you fail to run `git init` in the super repo. You also put the sub-repo (i.e. the directory containing .git, not the logical sub-module) in a sub directory of the super repo. That's not what is shown in the README and it is pretty surprising if ot works.

**Comment by JustDevZero** [comment]
@frej

Thanks for answering. 

I wrote the commands by memory, not "copy pasting". 

I made sure in both cases that the structure was like you say, in separated folders, like you said. 

The only difference was at the second time not adding the author map on the subrepo and adding the - --hg-hash in both conversions, sub and super.

**Comment by frej** [comment]
Without the exact commands I can't really try reproduce this, the author map should not screw this up, but it could be useful to see what happens with `--hg-hash` and `-A` in isolation.
