### ISSUE TITLE
Error occurs when including the -T option

### ISSUE THREAD

**Issue by jbouwens** [frej/fast-export#172]
Running the following command:
`/mnt/c/s/fast-export/hg-fast-export.sh -r /mnt/c/s/mainrepo/subrepo/ --force --plugin branch_name_in_commit=end -B /mnt/c/s/exported/mapped_branch_names.txt.uniq.txt -T /mnt/c/s/exported/mapped_tag_names.txt.uniq.txt -n`

And I get the resulting messages:

> Loaded 2 tags
> ...
> Exporting tag [2019 Spring R2] at [hg r1837] [git :1838]
> Issued 1 commands
> fatal: Branch name doesn't conform to GIT standards: refs/tags/2019 Spring R2

My mapped_tag_names.txt.uniq.txt:
"2019 Spring R2"="2019_Spring_R2"
"refs/tags/2019 Spring R2"="2019_Spring_R2"

It seems like it finds the map file (loads two tags), but can't find the tag 2019 Spring R2.

How do I resolve the 'fatal: Branch name doesn't conform to GIT standards: refs/tags/2019 Spring R2' error?

**Comment by frej** [comment]
It looks like you were the first person to try to remap a tag since more than two years, congratulations! :) Anyway, it should work now.
