### ISSUE TITLE
Unable to convert repository that has been used with the evolve extension

### ISSUE THREAD

**Issue by Mossop** [frej/fast-export#173]
Attempting to convert a changeset that has some obsolete changesets in it just fails with:

```
obsolete feature not enabled but 9 markers found!
Traceback (most recent call last):
  File "/Users/dave/workspace/tmp/fast-export/hg-fast-export.py", line 665, in <module>
    plugins=plugins_dict))
  File "/Users/dave/workspace/tmp/fast-export/hg-fast-export.py", line 499, in hg2git
    (revnode,_,_,_,_,_,_,_)=get_changeset(ui,repo,rev,authors)
  File "/Users/dave/workspace/tmp/fast-export/hg2git.py", line 81, in get_changeset
    node=binnode(revsymbol(repo,str(revision))) # We were given a numeric rev
  File "/usr/local/lib/python2.7/site-packages/mercurial/scmutil.py", line 624, in revsymbol
    raise _filterederror(repo, symbol)
mercurial.error.FilteredRepoLookupError: hidden revision '29' was rewritten as: adf5ac0c33aa
```

**Comment by frej** [comment]
As the crash is inside Mercurial's `revsymbol` this could be a bug in Mercurial. It could also be the case that `revsymbol` cannot be safely used on repos using the Evolve extension. If it is the latter I suspect fixing this would require a non-trivial amount of work to fast export.

**Comment by Mossop** [comment]
I'm not sure why the first line complains about obsolete not being enabled as I have the evolve extension enabled in my hg config. Does fast-export alter mercurials configuration in some way?

**Comment by frej** [comment]
It does not touch the Mercurial repo.

From the final exception I suspect (and that is just a guess) that the use of the evolve extension makes the linear and monotonic commit numbering to break down. That could be why it tells us that `29' was rewritten as: adf5ac0c33aa` and if that is what is happening, it will not be a quick fix in fast-export.

**Comment by Mossop** [comment]
Ok the way hg2git creates the ui object doesn't load all the hg configuration and so the evolve extension is disabled which triggers the warning. It turns out to be harmless though.
