### ISSUE TITLE
Script would fail with "python is not a working python 2.7 interpreter" message

### ISSUE THREAD

**Issue by Betalord** [frej/fast-export#176]
I've just installed TortoiseGit and latest python for Windows 10, am using cmd as my command prompt, and trying to run the script I get the following error:

```
$ /e/Eclipse/workspace/Supergalactix/fast-export/hg-fast-export.sh -r /e/Eclipse/workspace/Supergalactix/
python is not a working python 2.7 interpreter, please use the 'PYTHON' environment variable to specify the interpreter to use.
```

I have latest python installed:

```
$ python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
```

Any idea how to fix the problem?

**Comment by frej** [comment]
> Any idea how to fix the problem?

Make sure you meet the system requirements as described in the README.

**Comment by frej** [comment]
Closing as the the clarified README should be clear on requiring a Python 2.7.x and the error message tells how to specify it if it is not the default.
