### ISSUE TITLE
why does not it take effect after I run the below command?

### ISSUE THREAD

**Issue by YonglianQian** [frej/fast-export#177]
Here is my command performed, the `mystore` and `mecurial` are the folders in the desktop. `mecurial` is my hg repository, `mystore` is my initialized git repository.

> Administrator@vabqia928VM MINGW64 ~/Desktop/mystore (master)
> $ hg-fast-export.sh -r ../mecurial/
> Traceback (most recent call last):
>   File "C:/Users/Administrator/Desktop/MyGit/fast-export/hg-fast-export.py", line 6, in <module>
>     from mercurial import node
> ImportError: No module named mercurial
> git-fast-import statistics:
---------------------------------------------------------------------

> Alloc'd objects:       5000
> Total objects:            0 (         0 duplicates                  )
>       blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
>       trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
>       commits:            0 (         0 duplicates          0 deltas of          0 attempts)
>       tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
> Total branches:           0 (         0 loads     )
>       marks:           1024 (         0 unique    )
>       atoms:              0
> Memory total:          2360 KiB
>        pools:          2048 KiB
>      objects:           312 KiB

> ---------------------------------------------------------------------
> pack_report: getpagesize()            =      65536
> pack_report: core.packedGitWindowSize = 1073741824
> pack_report: core.packedGitLimit      = 35184372088832
> pack_report: pack_used_ctr            =          0
> pack_report: pack_mmap_calls          =          0
> pack_report: pack_open_windows        =          0 /          0
> pack_report: pack_mapped              =          0 /          0
<hr>
Then I use `git checkout HEAD`, and the new git repository generates nothing.

> Administrator@vabqia928VM MINGW64 ~/Desktop/mystore (master)
> $ git checkout HEAD
> error: pathspec 'HEAD' did not match any file(s) known to git
> 
My mercurial repository.<br>
[https://i.stack.imgur.com/ciKk8.png](https://i.stack.imgur.com/ciKk8.png)
Git repository.<br>  
[https://i.stack.imgur.com/9F8gX.png](https://i.stack.imgur.com/9F8gX.png)
Please give me some suggestions.

**Comment by frej** [comment]
Please take a look at the readme and make sure you have installed all required tools. From the error message it's pretty clear that your Python isn't finding the mercurial package.

**Comment by frej** [comment]
Closing this issue as it is user error, and it has already been (partially) covered by #143, #60, and #47.

**Comment by YonglianQian** [comment]
I am a newbie. thanks very much, you save me my day. @frej 

> Please take a look at the readme and make sure you have installed all required tools. From the error message it's pretty clear that your Python isn't finding the mercurial package.

After I run the below command, it works properly.
`pip install mercurial`
Thanks again.
Besides, Does this tool have an automatic synchronization function? which can automatically synchronize the Git repository with Mercurial repository when someone commits a new change to the Mercurial repository. Alternatively, I have to manually perform this process by using a custom bash command? Thanks.

**Comment by frej** [comment]
> Besides, Does this tool have an automatic synchronization function?

Are you asking if fast-export supports incremental conversions or if it
can monitor a Mercurial repository and trigger conversion when it
changes?

If it is the former, it does, just run fast-export again and it will
convert the new commits. If it is the latter, it does not, but you could
probably trigger an incremental conversion with a Mercurial hook.
