### ISSUE TITLE
Does this tool have an automatic synchronization function?

### ISSUE THREAD

**Issue by YonglianQian** [frej/fast-export#179]
Does this tool have an automatic synchronization function? which can automatically synchronize the Git repository with Mercurial repository when someone commits a new change to the Mercurial repository. Alternatively, I have to manually perform this process by using a custom bash command? Our team is not well ready for migrating the full project to GIT.  thereby we want to have a try to work on both repositories.
Sorry for any inconvenience.

_Originally posted by @YonglianQian in https://github.com/frej/fast-export/issues/177#issuecomment-553274964_

**Comment by frej** [comment]
Are you asking if fast-export supports incremental conversions or if it
can monitor a Mercurial repository and trigger conversion when it
changes?

If it is the former, it does, just run fast-export again and it will
convert the new commits. If it is the latter, it does not, but you could
probably trigger an incremental conversion with a Mercurial hook.
