### ISSUE TITLE
When re-running fast-export, error 'Branch [master] modified outside hg-fast-export' is shown.

### ISSUE THREAD

**Issue by otac0n** [frej/fast-export#21]
This is the command I'm using:

    hg-fast-export.sh -r C:/Migration/WorkingDir -A authors.map

Here's the actual error message:

    Error: Branch [master] modified outside hg-fast-export:
    e7443efd712a7dcff6296b975626f471e246c875 (repo) != None (cache)

Of course, I don't even have a 'master' branch in HG, I have a 'default' branch, which is then renamed to 'master' when exported to git.

This only happens when trying to catch up a previously exported repository.

**Comment by frej** [comment]
Check out commit 3c27c693e13482059966003dd6545941b942a97a, you can now rename tags and branches on the fly. This should at least solve @otac0n's problem.

**Comment by otac0n** [comment]
:+1:

**Comment by lenucksi** [comment]
I could repreduce a similar issue on a standard Linux Ext3 fs. The first export worked fine, however following invocations failed with 
`
Error: Branch [master] modified outside hg-fast-export:
b7a0f8f1a7f7235afc9080c897b6d1e66feb0315 (repo) != bb18327aca35e4958a62b46ed440ee8b9dc02c0b (cache)
`
command used was 
`
hg-fast-export.sh -s --hgtags --hg-hash
`
.git contains the following files: 
` hg2git-heads  hg2git-mapping  hg2git-marks  hg2git-state `

**Comment by frej** [comment]
> I could repreduce a similar issue on a standard Linux Ext3 fs. The
> first export worked fine, however following invocations failed with 
...
> command used was 
>
> hg-fast-export.sh -s --hgtags --hg-hash

Is the troublesome repo available somewhere? Does it have branch or tag
names not allowed by git? In that case use the -T and -B options to
rename them.

**Comment by lenucksi** [comment]
You can view the original at: 

http://hg.gajim.org/gajim/ 

and the mirror here:

 https://github.com/gajim/gajim

**Comment by lenucksi** [comment]
The branchnames look sane to me, although I have not yet consulted the Git documentation on that yet.

**Comment by frej** [comment]
@lenucksi After some testing it looks like --hg-hash has never worked in
incremental mode. The initial conversion works fine, the first
incremental step produces a warning and fails. The second incremental
import bails out with the error message you reported.

Try the fix-incremental-hg-hash branch and see if it fixes your
problem (you'll have to redo the initial conversion as your current git
repo is now broken). If it works for you I'll merge it to master.

**Comment by lenucksi** [comment]
@frej Thank you for the fast patch!
I've reimported another, smaller repo with the same parameters using your branch. I've imported it until some earlier tag using -m  and then executed the command described above to import until tip. 
Thus I should have simulated a valid incremental import.

As far as I can tell now, the incremental import worked fine.

**Comment by frej** [comment]
ok, pushed to master. Thanks for the testing @lenucksi.

**Comment by frej** [comment]
Commit b7cc6ab3bfecaea47105c23739b289461c2bf347 may also solve some "Branch ... modified outside hg-fast-export..." problems

**Comment by frej** [comment]
Considering that it now has gone almost half a year and no feedback I'll close this issue assuming it is fixed, feel free to reopen if that's not the case.
