### ISSUE TITLE
Convert branch with a new line symbol

### ISSUE THREAD

**Issue by fytov** [frej/fast-export#215]
Hello,

I'm trying to convert a repository (~7k revisions) from hg to git.
I'm having an issue with a branch name in the middle of hg repo(rev. 1500). The name contains a new line symbol (I don't know how it possible, but it's a fact). When commit on this branch is converted (step **Exporting simple delta revision**) I get an error **IOError: [Errno 22] Invalid argument.**

.git/fast_import_crash_<pid> didn't help me. It contains only first part of the branch name (before new line symbol)
Also, I'm using external file with branches names, but I don't know how to specify a new line symbol :(

Traceback:
```
master: Exporting simple delta revision 1835/7203 with 0/1/0 added/changed/removed files
Case 1656, 8785 -
Playlist:Timeline shows twice.: Exporting simple delta revifatal: Branch name doesn't conform to GIT standards: refs/heads/Case 1656, 8785 -
fast-import: dumping crash report to .git/fast_import_crash_15236
sion 1836/7203 with 0/3/0 added/changed/removed files
Traceback (most recent call last):
  File "C:/Users/A/fast-export/hg-fast-export.py", line 692, in <module>
    plugins=plugins_dict))
  File "C:/Users/A/fast-export/hg-fast-export.py", line 544, in hg2git
    plugins)
  File "C:/Users/A/fast-export/hg-fast-export.py", line 349, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding,plugins)
  File "C:/Users/A/fast-export/hg-fast-export.py", line 224, in export_file_contents
    wr(d)
  File "C:/Users/A/fast-export/hg-fast-export.py", line 46, in wr
    wr_no_nl(msg)
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 43, in wr_no_nl
    sys.stdout.write(msg)
```
Just tell me if you need some additional info.

Please feel free to share any ideas.

Alex

**Comment by chrisjbillington** [comment]
You should be able to use escape characters in the branch names file, such as `'\n'`. I believe hg-fast-export's default behaviour is to process the contents of branch mapping entries (same with author mappings) with `.decode('unicode_escape')` before doing anything else with them.

**Comment by fytov** [comment]
> You should be able to use escape characters in the branch names file, such as `'\n'`. I believe hg-fast-export's default behaviour is to process the contents of branch mapping entries (same with author mappings) with `.decode('unicode_escape')` before doing anything else with them.

I tried to use '\n' in a mapping file, but it doesn't work for me

**Comment by frej** [comment]
Have you looked at the "Frequent Problems" and considered what "My mapping file does not seem to work when I rename the branch git fast-import crashes on!" implies for your conversion?

**Comment by fytov** [comment]
@chrisjbillington thank you, I've put \n ("Firstline\nSecondline") in the right place fixed issue from the first message.
But I'm facing the same problem in another place and fix with '\n' doesn't solve it.

I got the same traceback but with a different error - **IOError: [Errno 32] Broken pipe**
`Case 66949 : Lower Level Navigation – Edit Menu / Find and Replace
Redesign UI: Exporting simple delta revision 2222/7203 with 0/6/0 added/changed/removed files
Traceback (most recent call last):
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 692, in <module>
    plugins=plugins_dict))
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 544, in hg2git
    plugins)
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 349, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding,plugins)
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 224, in export_file_contents
    wr(d)
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 46, in wr
    wr_no_nl(msg)
  File "C:/Users/A/fast-export/fast-export/hg-fast-export.py", line 43, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe`

This branch in TortoiseHg Workbench:
![image](https://user-images.githubusercontent.com/18198327/77539507-8bfbf200-6eb2-11ea-87dc-5624e88e8d2d.png)

Mapping file contains:
"Case 66949 : Lower Level Navigation – Edit Menu / Find and Replace\nRedesign UI"= "Replaced_name"

Can I use regex optional characters like ?*+ etc. ?

**Comment by frej** [comment]
> Can I use regex optional characters like ?*+ etc. ?

There is no special interpretation more than the `.decode('unicode_escape')` processing going on, so no extra escaping is needed for those characters nor can you use a regexp to match multiple branches.

Have you checked `git fast-import`'s crash report in `.git/fast_import_crash_<pid>` (search the man-page for CRASH REPORTS)? As fast-export runs asynchronously from `git fast-import` and your error is a broken pipe, the point at which `fast-import` quits is well before the last trace printout, as the closed pipe is only detected on the next write.

**Comment by chrisjbillington** [comment]
I wonder if it it might be an en-dash you've got in the branch name. I see that what we're doing with 'unicode-escape' doesn't seem to have the right behaviour on a UTF8-encoded en-dash:

```
>>> '–'.encode()
b'\xe2\x80\x93'
>>> '–'.encode().decode('unicode-escape')
'â\x80\x93'
>>> '–'.encode().decode('unicode-escape') == '–'
False
```

(`.decode('unicode-escape') is turning `\xe2` into `â`)

You should try replacing the en-dash with its unicode escape, `'\u2013'` and see if that works.

It seems like non-ascii characters in mapping files don't work correctly unless you set `--mappings-are-raw` (but then you wouldn't be able to have your newline character). This is less than ideal, maybe we can make it that unicode escape sequences are understood *and* other UTF-8 encodeddata is preserved.

**Comment by chrisjbillington** [comment]
This comment describes the `unicode-escape` behaviour that is messing up the en dash:

https://bugs.python.org/issue21331#msg217024

unicode-escape is annoying in that it shouldn't be considered a bytes to str conversion at all, it should have been made to convert str to str. Strikes me as a poorly thought out behaviour in Python 3.

**Comment by chrisjbillington** [comment]
@fytov can you test if #217 resolves the remaining issue?

**Comment by Liwoj** [comment]
I was converting hg repo with authors mapping containing unicode characters (Czech ý/ř etc) and was wandering why resulting repo has author names mangled (no errors tho). 

I can confirm, your PR fixes the issue!
