### ISSUE TITLE
hg -> git export in the same directory

### ISSUE THREAD

**Issue by kgofron** [frej/fast-export#216]
I have number of mercurial repositories on Debian (7,8,9,10) that need migration to gitlab. 
I was trying to do it in the same folder that original hg repo is located.
```
cd new-git-repo
git init
../../fast-export/hg-fast-export.sh -r . --force
git remote add origin https://github.com/xxx/new-git-repo
git checkout HEAD
```
However, this results in number of untracked files (all of the directories/files), and deleted files. The git checkout HEAD results in error
```
error: The following untracked working tree files would be overwritten by checkout:
	.hgignore
	Makefile
	config
	configure/CONFIG
```
Can fast-export be done in-place?

Clarification is much appreciated.

**Comment by frej** [comment]
> Can fast-export be done in-place?

Fast-export does not touch the working directory, so conversion can be done in-place, but git will consider the working directory to be dirty. See the _`git status` reports that all files are scheduled for deletion after the initial conversion_ question in the _Frequent Problems_ section of the README.

As your checkout will overwrite files which weren't put there by git, git warns (it is paranoid about losing your work). Please refer to the git documentation for how to do potentially destructive checkouts.

**Comment by kgofron** [comment]
Thanks for confirming, and it required git command
```
git reset --hard HEAD 
```
Full code for InPlace mercurial->git migration:
```
# migration
cd myHgRepo
git init
../fast-export/hg-fast-export.sh -r .
# cleanup
git reset --hard HEAD
cp ../.gitignore .
git remote add origin https://github.com/xxx/myHgRepo
git push -u origin master
```

########
Additionally, there is a difference between doing InPlace (actual folders/files are there)
```
../fast-export/hg-fast-export.sh -r . 
```
vs OutOfPlacecreating with git repository in new folder and the fast-export (folders/files do not exist
```
cd new-git-repo
./fast-export/hg-fast-export.sh -r  hg-repo
```
The 'git status' indicates  'deleted' folders which are only present when doing in the InPlace migration.

**Comment by frej** [comment]
Good that it worked for you. But as I said, the result you get from `git status` depends on what you have in the working directory, and as fast-export doesn't touch it, a forced checkout and/or a `git clean` is required to clean it up.
