### ISSUE TITLE
Debian 7 (hg=2.2.2, git=1.7.10.4, python=2.7.3)

### ISSUE THREAD

**Issue by kgofron** [frej/fast-export#218]
I have few dozens of Debian 7 systems, that need mercurial repositories migrated to gitlab with following versions:
```
hg 2.2.2
git 1.7.10.4
Python 2.7.3
```
I checked the release notes, and am guessing to use release v160914.

I tried v180317, and it completed conversion. Definitely newest (master) release does not convert. because of mercurial >=4.6 is required, but it is not clear from release notes which release is best suitable.

**Comment by frej** [comment]
I don't maintain that information. The published release notes on Github and `git blame` on the README is the your friend.

Considering that you appear to be doing one-off conversions, what stops you from cloning the Mercurial repos to a modern machine, and run the conversion on it? That way you can make use of the latest features of fast-export.

**Comment by kgofron** [comment]
The current hg repos are sitting at specific location of the Debian (7,8,9,10), and control specific hardware instruments. The updates to the software repos happens on that very specific hardware. We have about 60-100 mostly Debian systems, with each containing about 20-100 repos (hardware controllers). Doing conversion on yet another system would not track changes to the software/repo that controls hardware.
Perhaps there are better ways, but doing InPlace git repo in addition to hg (deprecated) repo, would give us gradual migration away from hg.

**Comment by frej** [comment]
I see, you know your systems best, but letting the conversion race against updates and then doing a switchover to git seems risky, but I gues you know what you are doing. I'll consider this issue closed for now.
