### ISSUE TITLE
fast-export hg repo with active branch other than default

### ISSUE THREAD

**Issue by kgofron** [frej/fast-export#219]
fast-export SHA1
```
commit 61d22307afb4bcbbb76d3e7ff8328e58f8dc714f (HEAD -> master, origin/master, origin/HEAD)
```
OS: Debian 10

My hg repository runs from srx branch
```
cam01$ hg branch
srx
```
There are 3 branches: srx, default, chx
``
cam01$ hg branches
srx                           18:3012b66fc65c
default                       16:8daf3f3a08f9
chx                            4:74919b4b5f24 (inactive)
```
After conversion to git repo, the git repository is parked on master branch (converted from default). This behavior is undesirable.
The -M flag is not suitable for this situation.

Is it possible to convert one branch (srx -> master)?
Otherwise, after conversion, I would like to be on the srx branch, but am not sure how to do this with fast export.

**Comment by frej** [comment]
> Is it possible to convert one branch (srx -> master)?

You can't just convert one branch.

> Otherwise, after conversion, I would like to be on the srx branch, but
> am not sure how to do this with fast export.

You can't do that with fast-export, by design fast-export does not touch
the working directory. Just use git checkout to check out the branch you
want.

**Comment by kgofron** [comment]
After fast-export, I am on the srx branch in git. However, my running hg repository is on the default branch. 
git checkout fails because files would be overwritten.
```
kaz@debian10:~Test$ git branch
  chx
* master
  srx
kaz@debian10:~/Test$ git checkout srx
error: The following untracked working tree files would be overwritten by checkout:
	.hgignore
	autosave/.README
	config
	records.dbl
	st.cmd
	unique.cmd
Please move or remove them before you switch branches.
Aborting
```
Typically, if I am doing fast export and hg repo is on the default, which is converted to git master. then I do 
```
git reset --hard HEAD
```
Which takes care of the problem for master branch. However, since I end on the git master branch, issuing 'git reset --hard HEAD' would change hg repository, and my running software.

I am not sure how to reset git  to srx/HEAD, without changing the actual files (hg repo).
===
Possible work around would be to do something on the hg side, and migrate srx branch to default...

**Comment by frej** [comment]
> I am not sure how to reset git to srx/HEAD, without changing the
> actual files (hg repo).

git checkout --force <branch> will checkout <branch> without caring
about overwriting files.

I must confess that I don't really understand what you are doing, are
you doing the conversion in place? If so, that's not recommended. If you
try you'll end up with problems looking like the ones I think you are
describing.

It's much better to do the conversion to a fresh new directory and when
that one is verified and the right branch checked out, replace the
original with it.

**Comment by kgofron** [comment]
```
git checkout --force <branch> will checkout <branch> without caring
about overwriting files.
```
This works.
```
I must confess that I don't really understand what you are doing, are
you doing the conversion in place? If so, that's not recommended. If you
try you'll end up with problems looking like the ones I think you are
describing.
```
My repos control hardware, and are integrated with hardware and system V on linux. It would be prone to errors, to convert elsewhere then replace ~5000 repositories controlling live hardware. The repos are running on over 50 servers. The repos generate several millions of live variables updating temperature, humidity, motor position, sensors, 2D detectors, ...

The issue can be closed.

**Comment by frej** [comment]
> My repos control hardware, and are integrated with hardware and system
> V on linux. It would be prone to errors, to convert elsewhere then
> replace ~5000 repositories controlling live hardware. The repos are
> running on over 50 servers. The repos generate several millions of
> live variables updating temperature, humidity, motor position,
> sensors, 2D detectors, ...

I see, so you must have some mechanism in place to stop your running
system from racing against the `git checkout --force` I guess?

> The issue can be closed.

Feel free to close it, right now I'm just satisfying my curiosity.

**Comment by kgofron** [comment]
```
...must have some mechanism in place to stop your running
system from racing against the `git checkout --force` I guess?
```
When conversion is in place on Linux, the control application is running without impact, since it is running from linux memory. Not a problem as long as I do not restart the control application, it will be fine. 
When controls is running on Windows it will lock the .dll files, which might have impact on running controls, during branch switch, ...
Arm, Mac, Raspberry Pi, VME, .... , I simply have not checked, and our deployment is minimal/none on these platforms.
