### ISSUE TITLE
AttributeError: 'branchcache' object has no attribute 'items'

### ISSUE THREAD

**Issue by boyenpeter** [frej/fast-export#225]
When I try to execute 
`$ ../fast-export/hg-fast-export.sh -r ../hg-repo/ -A ../authors`

I get

`Loaded 15 authors
Traceback (most recent call last):
  File "/cygdrive/c/dev/git-fast-export/fast-export/hg-fast-export.py", line 719, in <module>
    plugins=plugins_dict))
  File "/cygdrive/c/dev/git-fast-export/fast-export/hg-fast-export.py", line 535, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "/cygdrive/c/dev/git-fast-export/fast-export/hg-fast-export.py", line 480, in verify_heads
    for bn, heads in repo.branchmap().items():
AttributeError: 'branchcache' object has no attribute 'items'
/usr/libexec/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2360 KiB
       pools:          2048 KiB
     objects:           312 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =      65536
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------`

I am doing this in a cygwin terminal on Windows 10, and the python version is Python 2.7.16

**Comment by frej** [comment]
@chrisjbillington Do we have to bump the minimum supported version of Mercurial, as Mercurial 4.6 doesn't appear to have iter() only iteritems()

**Comment by boyenpeter** [comment]
If it helps these are my installed python packages:

certifi==2020.4.5.1
dulwich==0.19.16
hg-git==0.8.13
**mercurial==5.0.2**
pyxdg==0.26
urllib3==1.25.9

**Comment by chrisjbillington** [comment]
Looks like `items` was introduced as an alias for `iteritems` in 5.1. But `iteritems` still exists. Requiring mercurial 5.1 is a bit harsh, let's just use `iteritems` and not change required mercurial version.

My mistake in assuming branchmap was a dictionary! Pull request incoming.

**Comment by frej** [comment]
@boyenpeter: This should now be fixed in master, give it a try, reopen if it did not solve your problem.
