### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mbarkhau** [frej/fast-export#229]
It seems to me that the readme should start with copy and paste instructions to install the commands. Perhaps something like this:

```shell
$ git clone https://github.com/frej/fast-export.git
$ export PATH=$PATH:$PWD/fast-export/
$ mkdir repo-git
cd repo-git
git init
hg-fast-export.sh -r ../repo-hg
git checkout HEAD
```

**Comment by jowan** [comment]
Absolutely. The current readme suggests all you need is the shell script, which is not true.
_Please_ update the readme with proper installtion and useage instruction.

**Comment by frej** [comment]
The users of a tool like fast-export can be expected to know how to clone a git repo and run a shell script contained in that repo. Also, as fast-export is known to run on different operating systems, and from different shells, so step by step instructions covering all possible environments are not realistic.

**Comment by mbarkhau** [comment]
Oh man, just because most people know (and yes I did figure it out) doesn't mean that it wouldn't be convenient to have copy-and-paste instructions for the 90% use case.

Sorry for the inconvenience. No hard feelings, thanks for your work.
