### ISSUE TITLE
Failed to migrate from mercurial to git "fatal: Expected committer but didn't get one"

### ISSUE THREAD

**Issue by ivango-tr** [frej/fast-export#230]
Hi, We are trying to migrate mercurial repo to git with hg-fast-export.
The script crashes when we reach a branch with \n as a part of that branch name.
We use the mapping file and it seems that the relevant line, unlike the rest of the lines is ignored.

This is the error we are getting:

`fatal: Expected committer but didn't get one`

We tried the following:
1. Make sure we don't have a breaking symbol in the mapping files.
2. We ran without a mapping file.
3. Considered rename the branch in the mercurial and it seems too complicated.

Is there a workaround and what additional details can I provide?

**Comment by chrisjbillington** [comment]
Are you using a literal newline in the branch mapping file, or a `'\n'` escape? The latter should work, and the former will not.

**Comment by yevgeniyzh-etoro** [comment]
I will answer for Ivan - we just see \n without quote ' as part of the name of the branch in the mapping file. Bla bla \n foofoo

**Comment by yevgeniyzh-etoro** [comment]
there are spaces before and after the \n
and the weird part is it worked for a coleague a few months ago
can it be the export tool changed?

**Comment by frej** [comment]
> there are spaces before and after the \n
> and the weird part is it worked for a coleague a few months ago
> can it be the export tool changed?

Check the git fast-import crash report (search for "CRASH REPORTS" in
the man page for git fast-import) and see what fast-exports feeds to
fast-import.

**Comment by ivnago** [comment]
In my mapping file for branches, it was defined like this: "1234\n -My New Branch"="kiln/123 - My New Branch". As far as I know, the `sanitize_name` function returned a two-line name:
```
1234
 -My New Branch
```

It looks like it didn't find the match in the mapping file (I don't know why).
So after some digging in the code, I made some changes in this function ( `sanitize_name`), I change a regex to `([[ ~^:?\\\\*\r\n]|\.\.)` instead of `([[ ~^:?\\\\*]|\.\.)`. After the change, it still didn't find a match inside a mapping file but at least it was able to convert the branch name.

**Comment by frej** [comment]
> In my mapping file for branches, it was defined like this: "1234\n -My
> New Branch"="kiln/123 - My New Branch".

"kiln/123 - My New Branch" isn't a valid git branch name.

> It looks like it didn't find the match in the mapping file (I don't know why).

My first guess is that you're hitting the "My mapping file does not seem
to work when I rename the branch `git fast-import` crashes on!" case
described under "Frequent Problems" in th README, but it's my guess from
the limited information I have.

**Comment by frej** [comment]
No feedback in 90+ days, I assume this has been resolved.
