### ISSUE TITLE
there is no 'revsymbol ' in mercurial

### ISSUE THREAD

**Issue by SaboShao** [frej/fast-export#237]
fast-export/hg-fast-export.py", line 7, in <module>
  from mercurial.scmutil import revsymbol
ImportError: cannot import name revsymbol

**Comment by frej** [comment]
Please make sure that you meet the system requirements as documented in the readme, searching for the phrase ["cannot import name revsymbol"](https://github.com/frej/fast-export/issues?q=is%3Aissue+cannot+import+name+revsymbol) among the closed issues would have given you the answer.
