### ISSUE TITLE
Fatal: Empty path component found in input

### ISSUE THREAD

**Issue by sp-christian** [frej/fast-export#240]
Crash during import of [GNU Octave](https://hg.savannah.gnu.org/hgweb/octave/).

Most likely with this file path: `gui//Quint.pro`

```
  reset refs/heads/master
  commit refs/heads/master
  mark :13331
  committer Jacob Dawid <jacob.dawid@googlemail.com> 1301955138 +0200
  data 16
  M 100644 inline gui//Quint.pro
* data 415
```

[Crash report](https://gist.github.com/sp-christian/34360eeedaa3a1f68c21086b10ca7ae7)

**Comment by frej** [comment]
Christian <notifications@github.com> writes:

> Most likely with this file path: `gui//Quint.pro`

Looks very likely. I would try writing a plugin which sanitizes the
path. Just change the 'filename' field in the file_data dictionary in
the plugin's file_data_filter callback (See the README for the details).

**Comment by frej** [comment]
No response to review comments for the proposed patch in more than 90 days, closing without prejudice for inactivity.
