### ISSUE TITLE
git color settings may cause failure in final steps

### ISSUE THREAD

**Issue by ctarbide** [frej/fast-export#248]
Nice project, thank you guys.

Below is a simple fix for cases where git is configured for `color.branch=always`:

```diff
diff --git a/hg-fast-export.sh b/hg-fast-export.sh
index fd0ff53..c733ad2 100755
--- a/hg-fast-export.sh
+++ b/hg-fast-export.sh
@@ -208,7 +208,7 @@ cat "$GIT_DIR/$PFX-$SFX_MARKS.old" "$GIT_DIR/$PFX-$SFX_MARKS.tmp" \
 
 # save SHA1s of current heads for incremental imports
 # and connectivity (plus sanity checking)
-for head in `git branch | sed 's#^..##'` ; do
+for head in `git branch --no-color | sed 's#^..##'` ; do
   id="`git rev-parse refs/heads/$head`"
   echo ":$head $id"
 done > "$GIT_DIR/$PFX-$SFX_HEADS"
```

**Comment by frej** [comment]
The git manual says:
> You can also set it to `always` to ignore the difference between terminals and pipes. You’ll rarely want this; in most scenarios, if you want color codes in your redirected output, you can instead pass a `--color` flag to the Git command to force it to use color codes. The default setting is almost always what you’ll want.

I don't think it's fast-export's business to work around git configurations actively discouraged by the git manual. What is your use case for running with `color.branch=always`?

**Comment by ctarbide** [comment]
> The git manual says:
> 
> > You can also set it to `always` to ignore the difference between terminals and pipes. You’ll rarely want this; in most scenarios, if you want color codes in your redirected output, you can instead pass a `--color` flag to the Git command to force it to use color codes. The default setting is almost always what you’ll want.
> 
> I don't think it's fast-export's business to work around git configurations actively discouraged by the git manual. What is your use case for running with `color.branch=always`?

My use case is I use eshell terminal and it must use TERM=dumb, which prevents coloring of git commands.

I agree with you, it is not fast-export's business to handle an edge case like mine, fixing eshell is the way to go.

**Comment by frej** [comment]
> My use case is I use eshell terminal and it must use TERM=dumb, which prevents coloring of git commands.

If your eshell is the terminal inside Emacs you could write a small git wrapper which checks if the `$EMACS` environment variable is set and then adds `--color` to the command.

As we agree that this isn't really a problem with fast-export I will close this one.

**Comment by ctarbide** [comment]
I spent some time trying to figure out what was happening, the failure is not evident and it only happens in the last step, so I thought that adding '--no-color' was better than warmless and it would add resilience to the script, but the wrapper idea is indeed very nice, I can even build an elisp based command (as eshell/git) and it overrides the real thing in a non-instrusive and idiomatic way, then revert my git settings to 'auto', thanks!
