### ISSUE TITLE
Double Quotes in " branch names are causing the lock files failing to create on Windows (git-bash)

### ISSUE THREAD

**Issue by fahadash** [frej/fast-export#250]
I am getting a bunch of errors like the following

error: cannot lock ref 'refs/heads/branch_name_with_"double quotes"_failing': Unable to create 'C:/Code/Conversion/Repo/.git/refs/heads/branch_name_with_"double quotes"_failing.lock': Invalid argument

**Comment by frej** [comment]
According to Wikipedia `"` is not allowed in Windows filenames, and the way git works, branches are represented by a file in the filesystem. If you want to preserve the branch names you have to switch to an OS which allows the quotes. If you don't need to preserve the names you can use a branch mapping file and/or a plugin to rename the problematic branches.

Please close this issue if your question is answered.

**Comment by fahadash** [comment]
Thanks
