### ISSUE TITLE
mapping branches

### ISSUE THREAD

**Issue by admiralAwkbar** [frej/fast-export#267]
Hey! thanks for all the awesome work on this.
Im having an issue mapping a branch name that isn't good for git...
I'm running the command:
```bash
nohup /fast-export/hg-fast-export.sh -r /tmp/hg-repo/trunk --force -B ../branches.map -n | tee -a log.log &
```

The branches mapping looks like:
```bash
-- Start of branches.map --
"refs/heads/people^P/yye/rampup""="refs/heads/people/yye/rampup"
-- End of branches.map --
```

When the script errors it states the git branch name cannot be used...

Am I not sending the command right?

Any help is much appreciated!

**Comment by admiralAwkbar** [comment]
As soon as i pasted this i noticed the typo `""`. Hopefully that fixes it

**Comment by admiralAwkbar** [comment]
Even with the fix it still seems to bail out with the same error...

```bash
".git/fast_import_crash_11571" 3011L, 101696C                                                                                                                                   1,1           Top
fast-import crash report:
    fast-import process: 11571
    parent process     : 11570
    at 2021-07-16 20:01:15 +0000

fatal: Branch name doesn't conform to GIT standards: refs/heads/people^P/yye/rampup

Most Recent Commands Before Crash
```

Any help is much appreciated

**Comment by frej** [comment]
I see two potential issues here:

1. The branch name you should match is the Mercurial branch name, it probably does not start with `refs/heads/...`. What goes into the mapping file should be the Mercurial branch name.

2. Does the problematic branch name on the Mercurial side really contain the string `^P` i.e.  `\x5E\x50` or is actually `\x10`? If it is the latter, the string to map is `people\x10/yye/rampup` and not the pretty-printed representation.

**Comment by frej** [comment]
Additionally, the mapping should not include the `refs/heads/`-prefixes. Also check the "My mapping file does not seem to work when I rename the branch `git
  fast-import` crashes on!" section in the README for another potential gotcha.

**Comment by admiralAwkbar** [comment]
Hey! yeas i figured out some code changes to help solve this on my side

I will likely make a pr to see if they are a good fit for everyone
