### ISSUE TITLE
Get it on PyPI and install via PIP?

### ISSUE THREAD

**Issue by cykerway** [frej/fast-export#274]
This tool has been around for a while. Every time I use it I have to search this website. Any chance we can get it on PyPI so that users can install it from their command line via PIP?

Thanks

**Comment by frej** [comment]
I am not a PIP user (preferring to manage Python packages using my distribution's package manager and also to avoid shenanigans with malicious packages on PyPI), so pip-support would surely just slowly bit rot. Signed releases are provided for external packagers.
