### ISSUE TITLE
export project with submodules does not contain a valid uri

### ISSUE THREAD

**Issue by pietercardoen** [frej/fast-export#280]
When exporting a mercurial repository with a subrepository, the .gitmodules file contains:

[submodule "subrepo/subrepo2"]
      path = subrepo/subrepo2
      url = ../submodule2

while this should be

[submodule "subrepo/subrepo2"]
      path = subrepo/subrepo2
      url = https:://uri of subrepo

Current implementation of the submodule mapping file contains this syntax: "subrepo/subrepo1"="../submodule1". It should be better to have something like:
"subrepo/subrepo1"="../submodule1":"https://uri of subrepo"

Using this method, the .gitmodules file could be written correctly.

**Comment by frej** [comment]
The `.gitmodules` is correct. Git is perfectly able to resolve relative paths. If for example you push your super repo to `https://github.com/frej/super.git` and the subrepo to `https://github.com/frej/submodule2.git` everything will work fine. Additionally you get added flexibility, as a person can fork the project by just publishing `super` and `submodule2` on their own server and no references to the original server will remain.

If you absolutely need a full URI, you can use a `file_data_filter` in a plugin to modify `.gitmodules` before it is committed.
