### ISSUE TITLE
Reduce repository size

### ISSUE THREAD

**Issue by Strawl** [frej/fast-export#283]
Hi! 
The conversion works good! I really like it, incremental conversion also works find, even in large repositories. 
The only issue left, that I have, is that I don't really know how to deal with the repository size after the conversion. 
The 4 Gb big repository now converted to 20 Gb with git, which in the end was a 20Gb big pack file. 

This person had a similar issue:
https://stackoverflow.com/questions/6969385/why-is-my-git-repository-so-much-larger-than-mercurial-version#:~:text=But%20the%20Git%20repository%20is,3.4%20GB%20for%20Mercurial.

I tried running the following, but with no luck:
`git repack -a -d --window-memory 10m --max-pack-size 20m`
`git gc --aggressive`

Do you perhaps have an idea, how to tackle this problem?

**Comment by frej** [comment]
Fast-export is just a user of Git fast import. For questions on Git usage and performance, I suggest you pose your question to the [Git community](https://git-scm.com/community).
