### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by AAverin** [frej/fast-export#42]
Running hg-fast-export.py for my repository throws an error 'No --marks option given'.
People say that hg-fast-export.sh seems to be working fine, but I'm running on Windows, so no bash support.

**Comment by DanielGGordon** [comment]
That, or Cygwin should work.

**Comment by frej** [comment]
Seems to be solved as no action in over a year.

**Comment by DanielGGordon** [comment]
Yea I can confirm that I was able to run this tool on windows.
