### ISSUE TITLE
no checks in ident string

### ISSUE THREAD

**Issue by ewongbb** [frej/fast-export#43]
I'm currently trying to convert a large mercurial repo to git using fast-export.  After running it for some time, fast-export crashes with:

fatal: Missing > in ident string: test user <test@test.com 123456778 +1200
with the following traceback:
Traceback (most recent call last):
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 442, in <module>
    notes=options.notes,encoding=encoding))
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 364, in hg2git
    c=export_commit(ui,repo,rev,old_marks,max,c,authors,sob,brmap,hgtags,notes,encoding)
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 226, in export_commit
    export_file_contents(ctx,man,changed,hgtags,encoding)
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 140, in export_file_contents
    wr(d)
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "/home/cc/projs/fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe

**Comment by c4lliope** [comment]
Picking up this long-dead thread,
I had a similar issue parsing [Mozilla's source](https://hg.mozilla.org/);
a couple `<<address@place>` cases and similar.

I am [mirroring this code base], and [in this code base] I made a couple changes;
see the [change log](https://base.assembled.app/code/hg-quick-rebase/commits/branch/main).

[mirroring this code base]: https://base.assembled.app/dependencies/hg-fast-export
[in this code base]: https://base.assembled.app/code/hg-quick-rebase

[Open an issue here] should you experience similar issues,
and link the code base you need help on.

[Open an issue here]: https://base.assembled.app/code/hg-quick-rebase/issues/new

**Comment by c4lliope** [comment]
Once I searched around, I realized https://github.com/glandium/git-cinnabar handles these cases nicely,
and is a really speedy program.

I'm mirroring the code [here](https://base.assembled.app/dependencies/git-cinnabar).
