### ISSUE TITLE
ImportError: No module named mercurial

### ISSUE THREAD

**Issue by pronebird** [frej/fast-export#47]
Mercurial is installed in system.

```
➜  git_repo git:(master) which hg
/usr/local/bin/hg
```

**Comment by pronebird** [comment]
Solved with `sudo pip install mercurial`

**Comment by jglathe** [comment]
Well,  on a Synology I have the issue that the DSM installation breaks the symlink to mercurial. Wrote a script to set it again:

---snip---
#!/bin/sh
ln -f -s /volume1/@appstore/mercurial/env/lib/python2.7/site-packages/mercurial /usr/lib/python2.7/site-packages/mercurial
exit
---snip---

For whatever reason, pip and easy_install won't work there.
