### ISSUE TITLE
Empty path component found in input

### ISSUE THREAD

**Issue by henghamao** [frej/fast-export#48]
We used the tool for Pypy repository(https://bitbucket.org/pypy/pypy/downloads).
By using author-map, we worked out the issue "Missing < in ident string" at revesion 53977.
But there comes another error "Empy path component found in input":
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_25934
Traceback (most recent call last):
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 445, in <module>
    notes=options.notes,encoding=encoding))
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 367, in hg2git
    c=export_commit(ui,repo,rev,old_marks,max,c,authors,sob,brmap,hgtags,notes,encoding)
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 228, in export_commit
    export_file_contents(ctx,man,added,hgtags,encoding)
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 140, in export_file_contents
    wr(d)
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "/home/yicong.hyc/fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe

Looking at crahed report, we observed:
Most Recent Commands Before Crash
---------------------------------
  D pypy/translator/jvm/test/test_tuple.py
  D pypy/translator/jvm/test/test_unicode.py
...
  D pypy/translator/unsimplify.py
  M 100644 inline /doc/config/translation.lldebug.txt
* data 38

**Comment by frej** [comment]
>    We used the tool for Pypy repository(https://bitbucket.org/pypy/pypy/downloads).

>    But there comes another error "Empy path component found in input":
>    fatal: Empty path component found in input
>    fast-import: dumping crash report to .git/fast_import_crash_25934

The source repository is corrupt, it's not much fast-export can do about
that. To verify do:

$ hg clone https://bitbucket.org/pypy/pypy/downloads pypy-hg
$ cd pypy-hg
$ hg checkout -r dcc4f89c3872
abort: path contains illegal component: /doc/config/translation.lldebug.txt

**Comment by henghamao** [comment]
Are there any work around solutions?
We also tried git-remote-hg tool(https://github.com/felipec/git-remote-hg). The tool could sucessfully convert the project to git, though we didn't dig out how it solve the issue (skip the illegal path?). However, the speed is much slower than fast-export, and it could not incermental update with the further changes from hg repo.

**Comment by frej** [comment]
>    Are there any work around solutions?
>    We also tried git-remote-hg
>    tool(https://github.com/felipec/git-remote-hg). The tool could
>    sucessfully convert the project to git, though we didn't dig out how it
>    solve the issue (skip the illegal path?). However, the speed is much
>    slower than fast-export, and it could not incermental update with the
>    further changes from hg repo.

Googling on the hg error message gives:
http://bz.selenic.com/show_bug.cgi?id=3511

As that bug was in multiple released versions of Mercurial I wish they
would just have updated their libraries to automatically strip the
leading '/' and everything would just have worked. But we can't have
everything can we :)

But anyway, in a "healthy" repo there should be no absolute paths, so it
should be safe to always strip a leading '/' from the path. That fix is
implemented in b9b6f2a57ade75f06f06f1052c2148cb9b41f52b, and it appears
that git-remote-hg have a similar fix.

--Frej

**Comment by henghamao** [comment]
The fix solved the problem
However, there is another error "unable to resolve reference" appeared.
Since it looks like different issue, I will open a new one.
