### ISSUE TITLE
 unable to resolve reference ... : Not a directory

### ISSUE THREAD

**Issue by henghamao** [frej/fast-export#49]
We used the tool for pypy repo (https://bitbucket.org/pypy/pypy).
And after solved the issue "Empty path component found in input #48", there appeared another error:

Exporting tag [release-2.4.0] at [hg r73641] [git :73642]
...
Exporting tag [release-2.6.0] at [hg r77718] [git :77719]
Issued 79019 commands
error: unable to resolve reference refs/heads/stdlib-unification/py3k: Not a directory
error: Unable to lock refs/heads/stdlib-unification/py3k
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:     630000
...

The exporing process completed. But besides .git directory, there were no files exported.

**Comment by henghamao** [comment]
According to google search, one similar issue is git does not allow slash character in branch name.
I checked repo's branch name, it did have slash character in branch name, but didn't find "stdlib-unification/py3k" from the error message:

$hg branches |grep py3k
py3k                       78865:9b081ccd78af
py3k-qualname              72716:9f0e2a2c6084
py3k-ceil-floor            59071:6a1c5f8e7931
py3k-listview_str          58456:18626459a9b2

$hg branches |grep stdlib
vendor/stdlib              78042:a3b827ca23fa (inactive)
vendor/stdlib-3.3.5        72484:80b492d79663 (inactive)

**Comment by frej** [comment]
>    We used the tool for pypy repo (https://bitbucket.org/pypy/pypy).
>    And after solved the issue "Empty path component found in input #48",
>    there appeared another error:

As a direct conversion attempt of a local clone of
https://bitbucket.org/pypy/pypy crashes out with "Error: repository has
at least one unnamed head: hg r72634" you must have done something to
your local clone first, what was it?

**Comment by frej** [comment]
>    According to google search, one similar issue is git does not allow
>    slash character in branch name.
>    I checked repo's branch name, it did have slash character in branch
>    name, but didn't find "stdlib-unification/py3k" from the error message:

You have to run "hg branches" with -c to se all the branches

$ hg branches -c |grep stdlib
...
vendor/stdlib              78042:a3b827ca23fa (inactive)
...
vendor/stdlib-3.3.5        72484:80b492d79663 (inactive)
...
stdlib-unification/py3k    54912:4c6780e83b78 (closed)
...

**Comment by henghamao** [comment]
"Error: repository has at least one unnamed head: hg r72634"

I add "--force" parameter.

**Comment by henghamao** [comment]
We worked around the issue by fast-exporting only default branch.
hg clone https://bitbucket.org/pypy/pypy -b default
And used fast-export to work on local default branch.

**Comment by frej** [comment]
Commit 3c27c693e13482059966003dd6545941b942a97a adds renaming support for tags and branches which should allow you to convert all the branches.

**Comment by henghamao** [comment]
Great, now the issue was solved. :)
