### ISSUE TITLE
Converting .hg Subrepository

### ISSUE THREAD

**Issue by jurij** [frej/fast-export#51]
Hi,

is it possible, to convert subrepos from hg to git submodules? we are using a lot of subrepos right now, we need to convert them too. we would like to keep the history. 

best regards

**Comment by frej** [comment]
>    is it possible, to convert subrepos from hg to git submodules? we are
>    using a lot of subrepos right now, we need to convert them too. we
>    would like to keep the history.

Someone made a patch last November (pull request #38), but then did not
respond to requests for cleanups.

**Comment by devuxer** [comment]
Does anyone have the skillset and time to fix the code @daolis wrote? Seems a shame to lose someone's work if it's close to being ready.

Meanwhile, if someone has some kind of workaround, script, etc. to convert subrepos to submodules (even if it's not foolproof), please post it here. I've been spending a lot of time trying to track something down.

**Comment by lyubomyr-shaydariv** [comment]
Guys, any progress? It would let me get rid of my old hg repos I must use because of that.

**Comment by rishitborad** [comment]
I think commit 83e2d7a7f4436ef98bf1070b76168163c19fbfa6 in issue #38 is useful for me but i don't know how to update to that after I clone the fast-export repo. Can anybody help, please? 
I really need to convert subrepos from HG to GIT.

**Comment by lyubomyr-shaydariv** [comment]
Yay!
