### ISSUE TITLE
Branch name with Quotes

### ISSUE THREAD

**Issue by saadsami119** [frej/fast-export#53]
We are converting our hg repositories to git.  We are getting an error while converting it, the reason is that our branch name contains quotations characters. The branch name is [ Protocol "74 fixed" ].   It gives the following error.

Fatal: Unable to create 'C:/Dev/projectA/.git/refs/heads/Protocol "74 fixed "-Datum.lock': Invalid argument.

Could you please tell us how can we fix this error?

**Comment by frej** [comment]
> We are converting our hg repositories to git. We are getting an error
> while converting it, the reason is that our branch name contains
> quotations characters. The branch name is [ Protocol "74 fixed" ]. It
> gives the following error.

> Fatal: Unable to create 'C:/Dev/projectA/.git/refs/heads/Protocol "74
> fixed "-Datum.lock': Invalid argument.

"Protocol \"74 fixed\"" is not a valid git branch name, have a look at
the "Tag and Branch Naming" section of the README for how to rename
branches during conversion.

**Comment by ABFonseca** [comment]
I Know it's closed, but I have the same issue and looking at the README it only says to use mapping file but it does not explain how to escape the double quotes on the mapping file. I have tried put on the mapping file:
"P90130.1_"Supplies"_taking_too_long"="P90130.1_Supplies_taking_too_long"
and it fials, I also tried escaping the double quotes:
"P90130.1_\"Supplies\"_taking_too_long"="P90130.1_Supplies_taking_too_long"
and it still fails.

How can I solve this?

**Comment by frej** [comment]
\" is the correct way to escape the quotes. Have a look at the "My
mapping file does not seem to work when I rename the branch `git
fast-import` crashes on!" in the "Frequent Problems" section of the
README.
