### ISSUE TITLE
hg-fast-export bash script breaks when --force is used

### ISSUE THREAD

**Issue by gtristan** [frej/fast-export#57]
When invoking:
  hg-fast-export --force --quiet -r /path/to/hg/repo

The script bails out saying one should provide a '-r' option, which is provided.

I suspect the "break" statement in the bash loop collecting arguments is unintentional.

**Comment by frej** [comment]
Actually that matches the expected behaviour from the usage string. But I agree that it is stupid, feel free to submit a patch.

**Comment by frej** [comment]
No progress for a long time, closing...
