### ISSUE TITLE
Resolve SVN code?

### ISSUE THREAD

**Issue by hartwork** [frej/fast-export#58]
It seems to me that files
* `svn-archive.c`
* `svn-fast-export.c`
* `svn-fast-export.py`
* `Makefile`

are leftovers from a previous project. If they are, maybe delete them for clean-up.
There are two related entries in `.gitignore` as well:
* `svn-archive`
* `svn-fast-export`

Best, S

**Comment by frej** [comment]
Fixed in 2d9b147, thanks!

**Comment by hartwork** [comment]
Cool!
