### ISSUE TITLE
ImportError: No module named mercurial

### ISSUE THREAD

**Issue by dritter** [frej/fast-export#60]
I had to set the the `PYTHONPATH` explicitly: `export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"`.

I see two options for this problem:
Either documenting this in the `README`, or having the script figuring out the correct path. Mercurial itself does it like this:
```python
libdir = '../lib/python2.7/site-packages/'

if libdir != '@' 'LIBDIR' '@':
    if not os.path.isabs(libdir):
        libdir = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                              libdir)
        libdir = os.path.abspath(libdir)
    sys.path.insert(0, libdir)
```
It detects the path to the executable, and tries to find the according libpath.

**Comment by frej** [comment]
That you have to have mercurial installed to run hg-fast-export should be fairly self-evident, or else you will find out when the import fails.

If your python installation does not find site-packages by default, something is wrong with it. Are you by any chance running a hg-fast-export packaged by a distribution as it appears (from your proposed change) to be installed among the site packages?

**Comment by dritter** [comment]
Well. I installed mercurial and python with homebrew and cloned `hg-fast-export` in some folder.. IMHO it should have worked this way.

**Comment by frej** [comment]
Then something is broken with Homebrew.

Using the above way to figure out where site-packages are won't help you as '<directory-fast-export-is-in>/../lib/python2.7/site-packages/' will most probably not be where Homebrew installs python packages.

I know next to nothing about OSX, but a possible source of the error could be that you have two versions of Python installed, one from Homebrew and one from python.org. When you run fast-export you happen to get the one from python.org which, of course, knows nothing about the packages installed by Homebrew into its own python installation.

**Comment by dritter** [comment]
Ha. I think this is the problem. I already had an `/usr/bin/python` ([probably from OSX itself](http://www.opensource.apple.com/source/python/python-94/); homebrew packages go into `/usr/local/bin`). My installation of mercurial has the same problem, but (as python2.7 is a dependency) figures out the correct path itself.

You are right, that this is an issue of setting up python correctly, but especially on OSX it's not easy for the user..

To my solution:
Of course it won't be as simple as searching in `../lib/python2.7/site-packages/`. Speaking in shell, it could do an
    - `cd $(basename $(which python))`
    - `ls -1 ../lib/python*/site-packages`

Roughly something like this (it should find the matching site-packages etc)..

But I see your point that if the site-packages folder is in a different location than `../lib/python`, we are lost (`/usr/lib/python2.7/` - OSX-python - has no subfolder site-packages). So this solution won't work on OSX anyway..

**Comment by frej** [comment]
Just put /usr/local/bin before /usr/bin in your path or run fast export as:

PYTHON=/usr/local/bin/python hg-fast-export.sh ...

**Comment by aommm** [comment]
I also stumbled upon the same problem. My setup:
* MacOS 10.11
* Default python version
* Mercurial installed via `brew install mercurial`

I was helped by [this article](http://learnaholic.me/2013/02/01/converting-mercurial-hg-to-git-repository-on-mac/
).  Apparently it's not enough to have installed mercurial via homebrew, you also need to install a "python mercurial" or something:
```
sudo easy_install -U mercurial
```

This fixed it for me. I'm leaving this here for anyone else who might have the same issue.
