### ISSUE TITLE
git-fast-import fails with fatal: mark :137 not declared

### ISSUE THREAD

**Issue by lenucksi** [frej/fast-export#63]
At some point syncing/mirroring the hg-repo mentioned in https://github.com/frej/fast-export/issues/21#issuecomment-169655961 stopped with issue visible below.  [edited to add a space between link and "stopped" to make the link work/frej]

The system uses 
`git version 2.7.3 `
and
`Mercurial Distributed SCM (version 3.5.2)`

I would appreciate if you could have a look at it and maybe have an idea for a solution. 

Output of the sync-script:
```
Rufe von https://bitbucket.org/rndblnch/osx-presentation ab
Suche nach Änderungen
Keine Änderungen gefunden
Using last hg repository "../osx-presentation"
master: Exporting simple delta revision 138/146 with 0/1/0 added/changed/removed files
fatal: mark :137 not declared
fast-import: dumping crash report to .git/fast_import_crash_10250
Traceback (most recent call last):
  File "/home/git/fast-export/hg-fast-export.py", line 483, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/home/git/fast-export/hg-fast-export.py", line 383, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "/home/git/fast-export/hg-fast-export.py", line 235, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding)
  File "/home/git/fast-export/hg-fast-export.py", line 141, in export_file_contents
    wr(d)
  File "/home/git/fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "/home/git/fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
Everything up-to-date
Everything up-to-date
```

Contents of the mentioned crash report:
```
fast-import crash report:
    fast-import process: 10250
    parent process     : 10249
    at Sat Apr 2 18:58:15 2016

fatal: mark :137 not declared

Most Recent Commands Before Crash
---------------------------------
  commit refs/heads/master
  mark :138
  author Renaud Blanch <blanch@imag.fr> 1454618373 +0100
  committer Renaud Blanch <blanch@imag.fr> 1454618373 +0100
  data 27
* from :137

Active Branch LRU
-----------------
    active_branches = 0 cur, 5 max

  pos  clock name
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Inactive Branches
-----------------
refs/heads/master:
  status      : dirty
  tip commit  : 0000000000000000000000000000000000000000
  old tree    : 0000000000000000000000000000000000000000
  cur tree    : 0000000000000000000000000000000000000000
  commit clock: 0
  last pack   :


Marks
-----
  exported to /home/git/mirror/osx-presentation.git/.git/hg2git-marks.tmp

-------------------
END OF CRASH REPORT
```

**Comment by frej** [comment]
That particular comment does not say which repo is being converted, can you give me a link?

Also exactly which version of fast-export were you using when it crashed?

**Comment by lenucksi** [comment]
The repo being converted is: https://bitbucket.org/rndblnch/osx-presentation/overview the result is at https://github.com/lenucksi/osx-presentation-mirror
The used version of fast-export was: 
```
commit b7cc6ab3bfecaea47105c23739b289461c2bf347
Author: Frej Drejhammar <frej.drejhammar@gmail.com>
Date:   Sat Apr 2 15:01:45 2016 +0200
```

**Comment by frej** [comment]
I have tried to replicate your problem and failed. I did an initial import of revisions 1-137 using version 2d9b147a3e10b1b3d2bec7dffbeaf4bccdd027bf. Then continued the import using b7cc6ab3bfecaea47105c23739b289461c2bf347 and that works, so at least b7cc6ab3bfecaea47105c23739b289461c2bf347 is innocent.

But wait a minute, why does it say "Most Recent Commands Before Crash
---------------------------------
  reset refs/tags/nbxmpp-0.1
* from :1
"?

and " Marks exported to /home/gitmirror/python-nbxmpp.git/.git/hg2git-marks.tmp"

nbxmpp-0.1 is not in the source repo nor in the mirror, are you importing the right python repo? python-nbxmpp.git appears to have nothing to do with osx-presentation.

**Comment by lenucksi** [comment]
I guess that is mostly because I included the wrong fast-import crash report. Sorry, I've included the correct one now.

**Comment by frej** [comment]
ok, clearly git can't look up the marks. What do the hg2git-* files contain? Is there a mapping for :137 in hg2git-marks?

**Comment by lenucksi** [comment]
The file in question is empty...

**Comment by frej** [comment]
What about the other hg2git-* files? Have you by any chance recently changed your setup, for example cloned the git repos to a new location and started running the conversion in the cloned repo?

**Comment by frej** [comment]
If hg2git-marks is empty you are out of luck, and I can't do much to help you. Try a non-incremental conversion, as fast-export is deterministic you should get the same result again and recreate the missing files.

**Comment by frej** [comment]
No feedback on the latest suggestions for debugging (6 months ago), closing. Feel free to reopen the issue if the problem still remains.
