### ISSUE TITLE
Export script reports fatal error when hg branch name contains ampersand

### ISSUE THREAD

**Issue by stuarthillary** [frej/fast-export#66]
1. Use the default options for hg-fast-export.sh i.e. no mapping files are supplied
2. Try to convert a Mercurial repository that contains a branch whose name contains an ampersand character
3. Along with any messages warning of sanitized branch names, a message reads

`fatal: Needed a single revision`

**Comment by frej** [comment]
That's the intended behaviour, use mapping files to rename it. It's not in fast-export's interest to evolve into an AI which magically tries fix all the myriad of ways a user can misname a branch...

**Comment by frej** [comment]
I may have closed this too fast as I didn't like the proposed solution...

Are you sure that the ampersand is the problem? Can you provide a link to the hg repo you have a problem with or a sequence of commands to create a small repo having the problem?

**Comment by stuarthillary** [comment]
I have created a hg repo here with a branch name containing an ampersand:

https://bitbucket.org/stuarthillary/badmercurial

To replicate the problem I used a clean Ubuntu VM (15.04 LTS), installed git and mercurial using apt-get.

Clone the hg repository to ~/Code/BadMercurial
Clone fast-export to ~/Code/BadGit (and then deleted the .git folder)
Run `git init` inside BadGit folder
Run `./hg-fast-export.sh -r ../BadMercurial` inside BadGit folder

I see the output
`fatal: Needed a single revision`
`Warning: sanitized branch [Branch To Be Sanitized] to [Branch_To_Be_Sanitized]`
`master: Exporting full revision 1/3 with 1/0/0 added/changed/removed files`
`Warning: sanitized branch [Branch To Be Sanitized] to [Branch_To_Be_Sanitized]`
`Branch_To_Be_Sanitized: Exporting simple delta revision 2/3 with 1/0/0 added/changed/removed files`
`Fish&Chips: Exporting simple delta revision 3/3 with 1/0/0 added/changed/removed files`
`Issued 3 commands...`


Interestingly the Fish&Chips branch _has_ been created in the git repo.

I tracked the `fatal: Needed a single revision` message to the `get_git_sha1` method in hg2git.py when called for the Fish&Chips branch. `git rev-parse` is called for a sub-folder under the refs folder.

It looks like git branch naming isn't the specific problem here but _path names_ not allowing ampersand.

**Comment by frej** [comment]
> I tracked the fatal: Needed a single revision message to the
> get_git_sha1 method in hg2git.py when called for the Fish&Chips
> branch. git rev-parse is called for a sub-folder under the refs
> folder.
>
> It looks like git branch naming isn't the specific problem here but
> path names not allowing ampersand.

git rev-parse is called by os.popen, this is bad as it involves the
shell. This is especially ugly if you happen to have a branch named
"something&rm -rf /". The right fix is to use subprocess.check_output(),
the fix is in 463be093b01711d3538c9ad62ec95466e2ad1eed.

**Comment by frej** [comment]
@stuarthillary  Close the issue if the current head solves your problem, you'll also need c614ae776bd023095c91b849f4da268429b79455 to avoid the dreaded "Branch ... modified outside hg-fast-export..."

**Comment by stuarthillary** [comment]
Thanks, that seems to have sorted the problem
