### ISSUE TITLE
Create versions

### ISSUE THREAD

**Issue by straxhaber** [frej/fast-export#69]
If you create versions, I can make a [Homebrew](http://brew.sh) formula for fast-export so that more people will use it.

**Comment by bfontaine** [comment]
You can install `fast-export` with `brew install --HEAD homebrew/head-only/hg-fast-export` but it installs from the git HEAD which makes it harder to debug issues for our users; having versions is a good way to make sure we install stable code.

**Comment by scrimpist** [comment]
It seems as though frej is either no longer maintaining this tool, or is ignoring issues. If so, someone should fork this!

**Comment by straxhaber** [comment]
It seems as though frej is either no longer maintaining this tool, or is ignoring issues. If so, someone should fork this!

**Comment by frej** [comment]
I'm just busy with other things, I usually respond to user problems within a week. This issue got put on the back burner as it was a feature request. From my point of view, tagged versions would not help our users much. Either the version you have works for you or it does not, in which case you try the latest HEAD. Creating tagged versions is from my point of view just overhead, as basically each commit would be a new version. A tagged version would also imply, as @bfontaine says, that it is stable. I simply do not have the test suite and user reports to make that claim.

**Comment by straxhaber** [comment]
Hi @frej,

Sorry, I was a bit presumptuous when I said you might be ignoring issues. It had been three months since I posted it, and I figured you might just not use the issues tool.

As for tagged versions, you could tag them with something like "v0.x". The 0. would indicate it is an unfinished piece of software. Tagging it would allow us to include it in repositories like Homebrew. The purpose of the version tags is not to indicate that your software is stable as in "without bugs," but rather that it is stable as in "the version in the repository won't change every time there is a commit."

**Comment by frej** [comment]
Hi Matt,

If I were to tag versions I would probably just tag them with the date, like v160820, so the users could easily see how old the version they are running is. But for now, why not just cut a new version in Homebrew when the HEAD revision has not changed for a couple of weeks?

**Comment by straxhaber** [comment]
Hey @frej - it's your call, but I believe Homebrew expects upstream repositories to decide on their 'versions.' I'm pretty sure date-based version numbers would be fine. While I've contributed a few formula, I'm just a user of Homebrew.

Ideally, you'd tag a new version after either you've done some testing or waited a week or two to make sure there aren't lots of ugly bug reports because you broke something.

You have a useful tool and it would be nice to have it be more widely used.

**Comment by frej** [comment]
@straxhaber:  I've tagged a version now. Feel free to remind me the next time master changes...

**Comment by bfontaine** [comment]
Thank you @frej!

**Comment by straxhaber** [comment]
You beat me to it, @bfontaine! Thank you, @frej!

**Comment by imz** [comment]
Thanks for the tags. Tags are sometimes a bit more handy when needing to point to the base for a patch (represented as a branch; e.g., in our packaging [rules](https://github.com/imz/fast-export/blob/44795ee992b2e345ba86a39da0ff45295164909d/.gear/rules) for ALT).

And also good to name the package version in a distro.
