### ISSUE TITLE
Prepend the commit message with the branch name

### ISSUE THREAD

**Issue by cdimech** [frej/fast-export#75]
Add an option to prepend the commit message with the hg branch name, by specifying the switch `-c`.

New commit message will be of the form `[branch name]: [original commit message]`

**Comment by cdimech** [comment]
https://github.com/frej/fast-export/pull/76

**Comment by frej** [comment]
Please address my objections in the pull request (#76).

**Comment by frej** [comment]
Closing this issue as I don't see the need for this functionality. The wanted end result can be achieved greater flexibility with already existing functionality and tools (See the motivation in #76).
