### ISSUE TITLE
Support Windows Better

### ISSUE THREAD

**Issue by sprinkle131313** [frej/fast-export#82]
It seems the shell script is lightweight and just invokes the python script. It'd be nice if there was a batch script on Windows to do this, or simply move the work done by the shell script into the python script instead.

**Comment by frej** [comment]
> It seems the shell script is lightweight and just invokes the python
> script. It'd be nice if there was a batch script on Windows to do
> this, or simply move the work done by the shell script into the python
> script instead.

Personally I have no way to test on Windows, so for things like this I
have to rely on contributors.

**Comment by sprinkle131313** [comment]
Heh, who'll maintain it if you can't read batch script. Anyways removing the bash script all together and just making it entirely python is within your limitations. You can check if the python script works on posix systems and as long as you don't do anything idiotic, python will do what python does, making it portable. But if you're too lazy, i understand.

**Comment by frej** [comment]
I agree that going to 100% python is the right thing to do, but as bash "works for me"(tm) I'll probably never get around to implementing it. On the other hand, I'll gladly merge a patch that does away with the bash script if someone does the work, hint hint :)
