### ISSUE TITLE
How to best handle hg strip?

### ISSUE THREAD

**Issue by emilianbold** [frej/fast-export#86]
Hello (again),

My solution to minor unnamed heads it to just `hg strip` them from the incoming Mercurial repository.

One problem is that such an unnamed branch might have been converted to git before I decide to remove it. For example, the top commit [here](https://github.com/emilianbold/releases/commit/dc825c6f8a3ff51aec752a8fae87f2d17a6f3d23)

It seems possible to remove that commit from the git repository with `git reset`.

But how do I make hg-fast-export happy? (In order to be able to continue incrementally importing new commits).

I see that hg2git-heads as well as hg2git-marks might refer a stripped commit. Do I just hand-edit that?

**Comment by frej** [comment]
> But how do I make hg-fast-export happy? (In order to be able to
> continue incrementally importing new commits).
>
> I see that hg2git-heads as well as hg2git-marks might refer a stripped
> commit. Do I just hand-edit that?

Try it, if the commit is stripped upstream and removed from the state
files, I think it should work.

**Comment by emilianbold** [comment]
Well, it worked!

I stripped the commits from the mercurial repo, did a hard reset in the git repo, removed the line from hg2git-marks, updated the :master hash in hg2git-heads and finally the :tip in hg2git-state.

It seems a bit hardcore to do it manually. It would be nice to have a script for all this.
