### ISSUE TITLE
Error: repository has at least one unnamed head

### ISSUE THREAD

**Issue by wentasah** [frej/fast-export#9]
Hello,

when trying to convert http://www.arccore.com/hg/arc to git, I get the following error:

<pre>
fatal: Needed a single revision
Error: repository has at least one unnamed head: hg r2212
</pre>

I expect that in git terminology it complains about "detached head". Does anybody know how to fix it?

**Comment by klammerj** [comment]
Getting this, too. 
The repository is: https://bitbucket.org/alanmi/abc
I'm getting the error on one of the closed hg heads.
```
Loaded 20 authors
Error: repository has at least one unnamed head: hg r3098
git-fast-import statistics:
```

```
$ hg head
changeset:   3417:e176dbefc432
tag:         tip
user:        klammerj@a1.net
date:        Fri Oct 07 18:00:06 2016 +0200
summary:     Soften an overzealous assert

changeset:   3353:15f3be226d03
branch:      hier-npn_fast-exact
user:        Ana Petkovska <lee.anna.loo@gmail.com>
date:        Sat Jun 18 18:51:38 2016 +0200
summary:     Return the class representative of each function.

changeset:   3227:73982477d6f9
branch:      fxch_implementation
user:        Bruno Schmitt
date:        Wed May 11 19:41:31 2016 -0300
summary:     Add a new module which implements the fast extract with cube hashing (fxch) algorithm.

changeset:   2567:4fd5b8de5f9a
branch:      grigora/fixed-hang-issue-in-bm-command-1413034154897
parent:      2564:cae34096a164
user:        grigora <grigoraghanyan@gmail.com>
date:        Sat Oct 11 13:30:02 2014 +0000
summary:     Fixed "bm" command hang issue.

changeset:   2364:376aefd8fcdc
branch:      unfold2-dev
user:        Jiang Long <jiang.long@gmail.com>
date:        Wed Jun 04 23:21:13 2014 -0700
summary:     ci
```

```
$ hg head -c
```
[...]
```
changeset:   3098:dc1935e167d1
parent:      618:8d5cb5a0d1fc
user:        Baruch Sterin <baruchs@gmail.com>
date:        Sat Nov 21 01:04:03 2015 -0800
summary:     closing head created by mistake
```
how do I remove the closed hg heads?
(not a hg person)

**Comment by klammerj** [comment]
I tried the -f option now, but I end up with an empty directory. 
git log looks ok, but git status shows uncommitted changes, all of them deleted files. 
comitting did not fix it...

**Comment by frej** [comment]
> The repository is: https://bitbucket.org/alanmi/abc
> I'm getting the error on one of the closed hg heads.
>
> Loaded 20 authors
> Error: repository has at least one unnamed head: hg r3098

You either run with --force, name them on the hg-side (if you want to
preserve them), or do a clone (again on the hg-side) with -b to drop the
branches you are not interested in.

**Comment by frej** [comment]
> I tried the -f option now, but I end up with an empty directory.
> git log looks ok, but git status shows uncommitted changes, all of
> them deleted files.
> comitting did not fix it...

Just run 'git checkout -f <whatever-you-called-your-destination-branch>'
and all will be well. By design fast export does not touch your working
directory, so to git it looks like you have deleted all files, when in
fact they have never been checked out.

**Comment by klammerj** [comment]
Oh, sorry.. you're likely right...
In the meantime I've been successful using the hg-git
plugin. With that I ran into problems trying to push
via https(broken pipe.. ip timeout or a bug.. unsure..). 
using a bare local repo worked... then pulled from that 
with git and pushed to https...

**Comment by derek-austin** [comment]
Workaround (seen in http://stackoverflow.com/questions/30580756/get-rid-of-nameless-node-in-mercurial-repository):
~~~ bash
hg tags # Creates .hg/cache/tags2-visible
# Fix the nameless tag
sed -rie 's/^([^ ]+) $/\1 \1/' .hg/cache/tags2-visible
~~~

**Comment by james-mcguire** [comment]
How do you name a head on the HG side?

I have several closed (but named) branches, but I am still getting this error.

**Comment by james-mcguire** [comment]
Ah, I think the issue is that I have a named branch with multiple heads.  

See below link:
http://idontsov.blogspot.com/2017/12/fixing-repository-has-at-least-one.html

**Comment by caot** [comment]
> Thanks. `--force` did what I needed.

`--force` needs to be at the end of a command line.

`hg-fast-export.sh -r /path_to/some_repository.hg -A ~/hg_to_git/authors --force`

**Comment by dustwolf** [comment]
In my case, using `--force` resulted in almost all commits being absent from the resulting git repository.

I resolved the problem by merging the main branch containing most of the commits into the tip. Used TortoiseHg to visualise. This still discarded any unnamed branches that were not in the main branch, but I kept the commits that mattered.

**Comment by aercolino** [comment]
After trying out many different suggested solutions, this one is what worked for me (thanks to @frej): **make unnamed heads into branches** (my unnamed head was at revision 156)

```
(~/dev) $ hg clone repo repo-hg
updating to branch default
75 files updated, 0 files merged, 0 files removed, 0 files unresolved
(~/dev) $ cd repo-hg
(~/dev/repo-hg) $ hg update -r 156
22 files updated, 0 files merged, 66 files removed, 0 files unresolved
(~/dev/repo-hg) $ hg branch r156-fix-git-conversion
marked working directory as branch r156-fix-git-conversion
(~/dev/repo-hg) $ hg commit -m "Fix git conversion (unnamed head r156)"
(~/dev/repo-hg) $ hg update default
74 files updated, 0 files merged, 14 files removed, 0 files unresolved
(~/dev/repo-hg) $ cd ..
(~/dev) $ git init repo-git
(~/dev) $ cd repo-git
(~/dev/repo-git) $ ~/fast-export/hg-fast-export.sh -r ../repo-hg
... many lines without any error are expected here
(~/dev/repo-git) $ git checkout HEAD
(~/dev/repo-git) $ git status
On branch master
nothing to commit, working tree clean
```

**Comment by markgalassi** [comment]
aercolino's post is useful and gives the procedure, but it did not work for me when someone had *closed* that unnamed head.  The error message is the same (Error: repository has an unnamed head: hg r####).  If I run hg log -G I get an inkling that things might not work: there is a bit of a blank in the vertical line :-).  I ended up using "hg strip -r ####", and then doing it again 2 more times (!)  Thanks for this thread: it was very instructive.

**Comment by liudonghua123** [comment]
I tried to import https://eric-ide.python-projects.org/eric-code.html using github import tool, but it failed with unknown problems. And I tried this tool, it failed with the similar error, and `--force` option seems work for me.
