### ISSUE TITLE
hg-fast-export.sh fails when symlinked

### ISSUE THREAD

**Issue by cumuru** [frej/fast-export#93]
As I have to migrate hg repos from time to time I‘d like to have `hg-fast-export` in my path. For that purpose I cloned the repository in `/opt` and created a symlink `ln -s /opt/fast-export/hg-fast-export.sh /usr/local/bin/hg-fast-export`. Though I doubt it will matter: My OS is Ubuntu xenial.

Unfortunately this results in `hg-fast-export.py` being expected in `/usr/local/bin`. I added a `realpath` to determination of `$ROOT` in `hg-fast-export.sh` which does work. If there‘s a chance to get it merged I could create a PR. Are there any downsides on using `realpath`? Should `readlink` be preferred?

**Comment by frej** [comment]
I'd welcome a patch that makes fast-exporth do this correctly. I think readlink should be preferred as I recall a problem from work where realpath was not available on a colleague's Mac.

**Comment by cumuru** [comment]
Hum, no Mac over here, I can‘t check that. Nonetheless still willing to contribute.
Would something like
```
ROOT="$(dirname "$(greadlink -f "$(which "$0")" 2> /dev/null || readlink -f "$(which "$0")")")"
```
do the trick? It works on my Linux machine at least.
Or is there a more sophisticated way to do command fallback?
