### ISSUE TITLE
Fails on MacOS: "readlink: illegal option -- f"

### ISSUE THREAD

**Issue by lzkelley** [frej/fast-export#97]
```
daedalus:illpy lzkelley$ ../fast-export/hg-fast-export.sh -r ../_illpy/
readlink: illegal option -- f
usage: readlink [-n] [file ...]

Error: The option core.ignoreCase is set to true in the git
repository. This will produce empty changesets for renames that just
change the case of the file name.
Use --force to skip this check or change the option with
git config core.ignoreCase false
```

It looks like this parameter only works on linux.  They fixed [the issue here](https://github.com/yarnpkg/yarn/issues/2511) just checking what the OS is.

----

Temporary (local) Fix: removing the `-f` flag in `hg-fast-export.sh` works fine.

*Also*: I did have issues with the path resolution also.  If I run the script as `../fast-export/hg-fast-export.sh -r ../_illpy/` it couldn't find `hg-fast-export.py`... so I ended up just copying all of the scripts to my current directory (my new git repository) and running the script from there.

**Comment by frej** [comment]
Unfortunately the fix [you referred to](https://github.com/yarnpkg/yarn/issues/2511) just avoids the crash, it does not canonicalize the path.

Please try the [fix in this branch](https://github.com/frej/fast-export/tree/readlink-fix) and report back. It should behave as before the symlink support was added if you call fast-export by the full path  and give a proper error message if it is called via a symlink and `readlink` is missing or does not understand `-f.

If you want fast-export callable using a symlink you need to install coreutils using Homebrew or MacPorts.

**Comment by samtsai** [comment]
@frej I just tried the [readlink-fix-branch](https://github.com/frej/fast-export/tree/readlink-fix) and it worked for me, when using the full path!

**Comment by frej** [comment]
Thanks!
